### ISSUE TITLE
Windows Installation - Error on Run minion.js

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#103]
When installed and attempt to run within Windows environment the following error occurs
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\Windows\system32\bin\minion.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by computeronix** [comment]
As gordon discussed sounds like a reference issue   this should be pointing to the %APPDATA%\npm\node_modules\storj-bridge\bin      instead of the executing script location

**Comment by computeronix** [comment]
as a workaround

if you run storj-bridge.cmd while at the location %APPDATA%\npm\node_modules\storj-bridge 

The error goes away  (makes sense) :)

**Comment by Th3Van** [comment]
I'm having the same issue on Debian, but as a workaround I'm running "./bin/storj-bridge.js" from the main storj-bridge folder. (not the bin folder, just like computeronix described above)

**Comment by computeronix** [comment]
This also causes the minion service to crash over and over unless the workaround above is followed.

**Comment by super3** [comment]
Not going to support Bridge on Windows. Redis does not run on windows, and many other issues. Please run on VM with vagrant setup.
