### ISSUE TITLE
Standardized Ports

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#105]
For systems without UPNP (or dont want it enabled)

Have standardized ports as default rather than 0.

https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Registered_ports

Use the defaults or whatever gets approved by IANA

skunk suggested the following (for the client but can easily be adjusted for the bridge)

In the above example, storjshare will use port 4000 for the p2p communication. On port 4001, the built-in tunnel server will wait for a tunnel request and open a tunnel port between 4002 and 4004 if needed. Specifying "forward": false will disable UPNP.

https://storj.readme.io/docs/storjshare-troubleshooting-guide#port-forwarding

Recommend to register at least the two service ports https://www.iana.org/form/ports-services

Once registered those those two ports can be default (whatever ports IANA assigns)

The tunneling ports will most likely be unofficial (depending on what you work out with IANA)

**Comment by super3** [comment]
Duplicate issue.
