### ISSUE TITLE
Need to run integration tests with docker compose

### ISSUE THREAD

**Issue by niahmiah** [Storj/bridge#110]
Currently integration tests try to spin up a storj network to test against, inside of the mocha test.  This includes spinning up a farmer, and a bridge (which forks minion processes).

I suggest that instead, integration tests be run inside of docker containers, linked using docker compose.
Docker compose yml can include all of the information to spin up a network with mongo, rabbitmq, several farmers, and a bridge. Docker provides environment variables to bridge to locate the other linked services. The integration tests can be run against the containers.

Additionally, this will further enable minions to be broken out from the bridge process later, and not have to start and stop with bridge.

**Comment by super3** [comment]
@niahmiah Any progress on this?

**Comment by niahmiah** [comment]
@super3 wip, see https://github.com/Storj/bridge/commits/feature/110-integration-testing-with-docker-compose
