### ISSUE TITLE
Implement shard redundancy

### ISSUE THREAD

**Issue by bookchin** [Storj/bridge#118]

**Comment by super3** [comment]
There are two ways to handle this.

1. Have the user upload multiple redundant unique shards directly to the farmers. 
2. Have the user upload to the first set of farmers. Then have to bridge tell the redundant farmers to go get the data from the first set, and audit the data immediately. 

I think the performance hit for #1 is too great, and warrants the extra complexity introduced by #2.

**Comment by super3** [comment]
Yay!
