### ISSUE TITLE
Add .json to config files

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#122]
To standardize config (similar to cli) rename it from "devel" to config.json   (at least this is what the default looks like on windows)

**Comment by bookchin** [comment]
The current setup is designed to allow for many different configurations based on environment. For instance mine:

```
gordon@gordonhall ~/.storj-bridge/config
> $ ls
devel  test  __tmptest
```

Specifying the `NODE_ENV` environment variable will select one of these configs, the default is `devel`.

**Comment by computeronix** [comment]
after discussing with Gordon it was determined to do the following

add environment variable NODE_ENV     for production environments set it equal to production

then the file %USERPROFILE%\.storjshare\config    then the file will be labeled  production

Request to change configuration file to add .json to these auto-generated files

**Comment by super3** [comment]
Based on my discussion with @bookchin this would cause lots of issues, and can't make this change.
