### ISSUE TITLE
Apply reed Solomon erasure code shards for uploads

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/bridge#13]

**Comment by super3** [comment]
Do we want to implement Reed-Solomon at this stage in test? And do we want to implement it for all files. There is overhead involved in preping, negotiating, and distributing each one of those files. Might not even make sense for files less than a few megabytes. 

Worth some discussion, but I think we should implement simple redundancy(x4) in the API and client, and at a later date add Reed-Solomon client side with simple redundancy set to 1.

**Comment by gordonwritescode** [comment]
This no longer belongs here, since bridge will no longer proxy uploads. We'll lean on the client to perform this work.
