### ISSUE TITLE
upload shard Failed

### ISSUE THREAD

**Issue by wyh136** [Storj/bridge#133]
`[info]   Adding shard metadata for bf5f9d1a8904e5dba7f4faca1868c87d92eb0fc4 to frame`</br>
`[warn]   Failed to upload shard...`</br>
`[error]  <html>`</br>
`<head><title>502 Bad Gateway</title></head>`</br>
`<body bgcolor="white">`</br>
`<center><h1>502 Bad Gateway</h1></center>`</br>
`<hr><center>nginx/1.10.0</center>`</br>
`</body>`</br>
`</html>`

**Comment by super3** [comment]
This issue should go in this repo: https://github.com/Storj/core
