### ISSUE TITLE
Ban bad nodes

### ISSUE THREAD

**Issue by wyh136** [Storj/bridge#134]
.......
[warn]   Failed to transfer shard, reason: read ECONNRESET....
[info]    Retrying shard transfer,..............
[warn]   Failed to transfer shard, reason: read ECONNRESET....
[info]    Retrying shard transfer,..............
[warn]   Failed to transfer shard, reason: read ECONNRESET....
[info]    Retrying shard transfer,..............
.......
Trying to send shard to a bad reciver in many many times.
Can you add this bad node to local black-list?

**Comment by super3** [comment]
Please put this issue in the proper repo here: https://github.com/Storj/core and follow the issue template. There general thought is that this looks just like an issue we already fixed, make sure you are running the most current version.
