### ISSUE TITLE
Duplicate key error E11000

### ISSUE THREAD

**Issue by super3** [Storj/bridge#136]
Opened for @airatru https://github.com/Storj/bridge-gui/issues/61 

/usr/local/lib
├── storj@1.3.5 
├─┬ storj-bridge@0.9.3
│ └── storj@1.3.5 
└─┬ storjshare-cli@4.0.4
└── storj@1.3.5

v4.4.7

Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

Actual Behavior

{"level":"error","message":"E11000 duplicate key error index: __storj-bridge-test.shards.$hash_1 dup key: { : \"1e3731774c47bd082c6740dd910c3223da75d6c1\" }","timestamp":"2016-06-30T13:12:08.867Z"}

Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Run storjshare-cli on linux jessie (for rpi3)
Wait
Wait a bit more

**Comment by harryio** [comment]
Yup! Trying to create shard from an Android client and facing the same issue. 

```
{"error":"E11000 duplicate key error collection: bridge.usernonces index: user_1_nonce_1 dup key: { : \"user@user.com\", : \"631720e5-f033-4d22-b61c-e56499871117\" }"}
```

**Comment by bookchin** [comment]
I bet the bridge has an index on the hash property so this happens when a duplicate shard is generated. Curious, what were you trying to upload?

**Comment by niahmiah** [comment]
This can be addressed by using findAndModify with upsert:false, instead of creating a new document. With the new retry logic, this is likely to happen right? You just want to make sure the shard exists in mongo, not overwrite it. Since everything is content-addressable, there should never be a need to update, so if it exists or is created, return success to client.

~Ian Patton

**Comment by harryio** [comment]
@bookchin I'm just trying to upload an image captured from the device.

**Request**
```
D/OkHttp: --> PUT https://api.storj.io/frames/578b418da912a9a1569fad90 http/1.1
D/OkHttp: Content-Type: application/json; charset=UTF-8
D/OkHttp: Content-Length: 773
D/OkHttp: x-signature: 3046022100bf8d9edaaa5e41e705d297d8cb3b557c51a19e0178202468c79da1e9f602d649022100eb249193ccb52b729bc088d8d20cdf68725fbcd0b4f02e309bebf2fa807f537d
D/OkHttp: x-pubkey: 04906620ebcd59d352ae414087ab39dadb513e69fc7391d335d0fbcb5223dfa6e74b03249704a065b19421439e336379b577851c013d6608785cc10287119217bb
D/OkHttp: {"__nonce":"f62edbc0-4578-4243-8c13-736e9adf8831","challenges":["1c69ccbf988d66a93bff553e94911d8b","13b06d75442c8e31de69254016caea1e","c281f94968767e7bd208271579982c11","2dab449a2da934419779c7959a623043","4be84d535a33a24a48827ff5518d94e5","839c6290482b2bb168cb75d7ffa6b0b7","5077af1d2f2ee31fbbaa1a64dd22369f","a61283973ef44388ee770cc831e0974f"],"hash":"668f64d408b9429fdb89a7472aef139e04986ab9","index":0,"size":3973104,"tree":["f9a97ffc6131a6db2bbc2fc1042708646d8c7996","c908ea61ce9467fd8a313e0183e81b77d61e84ab","d7934eadbd7e58c8d798708baafa3c2e2deba1b8","0bb14218daa69f2ab240bacbefe681050809ea6a","1387a9ed62100775f6f19319072aaf1a791a6d08","4421a44abb4d1e1ee604a3a5bac827ab20bbf24c","3434f757671454331c1f9c5be1c2bc0c1291a820","97b7a471db741996a37ccf5e13630f5905458ad9"]}
D/OkHttp: --> END PUT (773-byte body)
```

**Response**
```
D/OkHttp: <-- 400 Bad Request https://api.storj.io/frames/578b418da912a9a1569fad90 (11604ms)
D/OkHttp: Server: nginx/1.10.0
D/OkHttp: Date: Sun, 17 Jul 2016 08:28:52 GMT
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Content-Length: 170
D/OkHttp: Connection: keep-alive
D/OkHttp: X-Powered-By: Express
D/OkHttp: Vary: Origin
D/OkHttp: Access-Control-Allow-Credentials: true
D/OkHttp: ETag: W/"aa-ICO5qKCJq3HmEjTiLc5fTw"
D/OkHttp: OkHttp-Sent-Millis: 1468744131664
D/OkHttp: OkHttp-Received-Millis: 1468744132481
D/OkHttp: {"error":"E11000 duplicate key error collection: bridge.usernonces index: user_1_nonce_1 dup key: { : \"user@user.com\", : \"f62edbc0-4578-4243-8c13-736e9adf8831\" }"}
D/OkHttp: <-- END HTTP (170-byte body)
```

**Comment by bookchin** [comment]
Oh, yours is different @harryio - yours looks like using a duplicate nonce.

**Comment by harryio** [comment]
@bookchin I don't see how that can be duplicate as I was previously sending Unix timestamp as the nonce value and was getting the same error. So, then I tried by sending the UUID as nonce value(see the Request and Response nonce values from my previous comment) and I'm still getting this error. I started getting this error just recently. I was trying the same call a few days back and did not encountered any error.

**Comment by bookchin** [comment]
@niahmiah does this look to you like there is a unique index on the user?

**Comment by super3** [comment]
@harryio Your error is unrelated. Please create a new issue.

**Comment by bookchin** [comment]
This actually belongs in Storj Share CLI, but I don't think it is an issue anymore.
