### ISSUE TITLE
User endpoint returns internal server error for bad POST

### ISSUE THREAD

**Issue by NutterzUK** [Storj/bridge#139]
### Package Versions
```
Using the live API: base url: / api version: 0.9.3
https://api.storj.io/users
```

### Expected Behaviour

If the user posts a bad request, e.g a user without a password property, the bridge should respond with a 401 Unauthorized, preferably describing the problem if possible.

### Actual Behaviour

The server responds with a 500 code and:
```
{
{"error":"Invalid email or password"}
}
```

### Steps to Reproduce

Open up postman, import the attached postman collection and send the "bad request". Or, just send a request to the server with:
{"email":"goo@goo.com"}

POSTMAN LINK: http://www.spindroid.co.uk/Storj.postman_collection.json

The log from the java client I am working on which will describe the problem:

1 * Client out-bound request
1 > POST https://api.storj.io/users
1 > Accept: application/json
1 > Content-Type: application/json
{"email":"goo@goo.com"}
1 * Client in-bound response
1 < 500
1 < Server: nginx/1.10.0
1 < ETag: W/"22-PKDJ75jnh4cDjNVcKSeBGg"
1 < Access-Control-Allow-Credentials: true
1 < Connection: keep-alive
1 < Vary: Origin
1 < Content-Length: 34
1 < Date: Sun, 03 Jul 2016 14:20:22 GMT
1 < X-Powered-By: Express
1 < Content-Type: application/json; charset=utf-8
1 < 
{"error":"Not a string or buffer"}

**Comment by NutterzUK** [comment]
Related issue so i'll put it here. If the user already exists, you also get a 500:
1 * Client out-bound request
1 > POST https://api.storj.io/users
1 > Accept: application/json
1 > Content-Type: application/json
{"email":"goo@goo.com","password":"b63f5c381af434e79666e3f5bf2ea5d236b2da80e26cf0b6408268a7e2d5a6f4"}
1 * Client in-bound response
1 < 500
1 < Server: nginx/1.10.0
1 < ETag: W/"27-Per6zhQ1oGJhNxkiUhDq3w"
1 < Access-Control-Allow-Credentials: true
1 < Connection: keep-alive
1 < Vary: Origin
1 < Content-Length: 39
1 < Date: Sun, 03 Jul 2016 14:22:10 GMT
1 < X-Powered-By: Express
1 < Content-Type: application/json; charset=utf-8
1 < 
{"error":"Email is already registered"}

com.sun.jersey.api.client.UniformInterfaceException: POST https://api.storj.io/users returned a response status of 500 Internal Server Error

**Comment by bryanchriswhite** [comment]
i believe this is actually a bug rather than RESTful negligence 👍

**Comment by bookchin** [comment]
POST /users is not a protected endpoint, so missing parameters should actually be a 400 Bad Request - not 401 Unauthorized. But this is still a bug.
