### ISSUE TITLE
Minion startup should be separate from bridge

### ISSUE THREAD

**Issue by niahmiah** [Storj/bridge#144]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

Minion startup should now be separate from bridge, so that a minion does not restart with bridge.

```

```

### Actual Behavior

Currently minions are spawned by bridge on startup, and stop with bridge on shutdown.

```

```

### Steps to Reproduce

Not provided, as this is feature request, not a bug.

**Comment by super3** [comment]
@niahmiah Can you weight this in Waffle?

**Comment by niahmiah** [comment]
This is already done on the branch with the docker compose work

**Comment by bookchin** [comment]
#218
