### ISSUE TITLE
Uploading file returns error 502 "Bad Gateway"

### ISSUE THREAD

**Issue by harryio** [Storj/bridge#146]
Trying to upload file through [Storj Api] (https://app.storj.io/#/dashboard/api-docs?_k=qc1mh8) to the endpoint `/frames/{frame_id}`from an android client which returns with an error `502 Bad Gateway`.

**Response for /frames/{frame_id}**
```
D/OkHttp: Content-Length: 588
D/OkHttp: x-signature: 30450221008c898ccc052163daf5a61e94d2320f87637f01ec0177ade9914b0a0ccebf6bb1022064567d08ba0288c54d436bed810671e9d5214bbb8ae27e8176d98012370eda92
D/OkHttp: x-pubkey: 04aca9ce9f3bb2919c5e8df1bdc30684d966bc924f7a8d1cb11935267505a32cffb22326aa491616bbe2fac7ad238158d36a5d164b6acc9b04d4e0de7acc112829
D/OkHttp: {"__nonce":1467925467538,"challenges":["da9772ab71320844a8b065bcb3855fd193146fe0f97eca29548b8915edb0d3f9","ed6ceb5080164505c8160ffef40f5b0ac5d714cb884f4922f9d97baaa416e8c9","5ff19a40f194a86ee37d798f317a32b133d8a16708eb0d4e76657b70a79ec1aa","4eaab9b6932e8182f0dbcbc8c509ae7d778c9b262913c24696c2c83048b101eb"],"hash":"cba1c79e1fad38b44274f3266632d51018b2cbfc2913fbf1e40201c0fcd5a5b1","index":0,"size":2097155,"tree":["e376997857897a8254ed0f6befad1920321c8e89","b5422a71649ff4f031b213ba4032b07877d3988d","7e9617acd6d1d9cfac0013c6ade65b1a8cd76e2a","871fdb1239a7acfa473efdb9ab01371bdfb1b828"]}
D/OkHttp: --> END PUT (588-byte body)
D/OkHttp: <-- 502 Bad Gateway https://api.storj.io/frames/577ec3dd7a80fe79096871d5 (506ms)
D/OkHttp: Server: nginx/1.10.0
D/OkHttp: Date: Thu, 07 Jul 2016 21:04:31 GMT
D/OkHttp: Content-Type: text/html
D/OkHttp: Content-Length: 173
D/OkHttp: Connection: keep-alive
D/OkHttp: OkHttp-Sent-Millis: 1467925467631
D/OkHttp: OkHttp-Received-Millis: 1467925468094
D/OkHttp: <-- END HTTP (173-byte body)
```

The frame id is generated from the call from endpoint `/frames` which is successful executed.

**Response for /frames**
```
D/OkHttp: --> POST https://api.storj.io/frames http/1.1
D/OkHttp: Content-Type: application/json; charset=UTF-8
D/OkHttp: Content-Length: 22
D/OkHttp: x-signature: 304402204190affc4dd275e39fd84e309842d97b27c431ac46b447fbcb8ff708d321ed880220282b81fdd644a00c36644e4fc4d29a22a05f251043bf6a58590c5fcf66ac0b9e
D/OkHttp: x-pubkey: 04aca9ce9f3bb2919c5e8df1bdc30684d966bc924f7a8d1cb11935267505a32cffb22326aa491616bbe2fac7ad238158d36a5d164b6acc9b04d4e0de7acc112829
D/OkHttp: {"__nonce":1467925466}
D/OkHttp: --> END POST (22-byte body)
D/OkHttp: <-- 200 OK https://api.storj.io/frames (477ms)
D/OkHttp: Server: nginx/1.10.0
D/OkHttp: Date: Thu, 07 Jul 2016 21:04:29 GMT
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Content-Length: 110
D/OkHttp: Connection: keep-alive
D/OkHttp: X-Powered-By: Express
D/OkHttp: Vary: Origin
D/OkHttp: Access-Control-Allow-Credentials: true
D/OkHttp: ETag: W/"6e-1TDBgEJtMhSiPu+kv1SCBg"
D/OkHttp: OkHttp-Sent-Millis: 1467925466292
D/OkHttp: OkHttp-Received-Millis: 1467925466719
D/OkHttp: {"user":"me@harryio.com","shards":[],"created":"2016-07-07T21:04:29.657Z","id":"577ec3dd7a80fe79096871d5"}
D/OkHttp: <-- END HTTP (110-byte body)
```

The file to be uploaded is first padded with 0's to make it's size to the nearest power of 2 which then is encrypted and then split into appropriate parts before uploading to the server. The hash is `SHA256` digest of the encrypted file part and size is the length of byte array of the file part.

**Comment by NutterzUK** [comment]
@harryio - It looks like we may both be working on something similar as I am making a Java client and you are making an Android client.. can I ask if your project is open source? My Java client is available on git, perhaps we can work together on one rather than duplicating it. 

My client is also getting this same error. I haven't yet split the file up etc, but I just tried testing the endpoint manually. It went like this:

Create frame to get the ID
REQ
```
1 * Client out-bound request
1 > POST https://api.storj.io/frames
1 > Accept: application/json
1 > Authorization: basic XXXXXXXX[BLOCKED OUT]XXXXXXX
```

===
RESP
```
1 * Client in-bound response
1 < 200
1 < Server: nginx/1.10.0
1 < ETag: W/"6f-kQXv0vMeBrGxLo8+IIHZyA"
1 < Access-Control-Allow-Credentials: true
1 < Connection: keep-alive
1 < Vary: Origin
1 < Content-Length: 111
1 < Date: Fri, 08 Jul 2016 21:51:25 GMT
1 < X-Powered-By: Express
1 < Content-Type: application/json; charset=utf-8
1 < 
{"user":"myemail@myemail.com","shards":[],"created":"2016-07-08T21:51:25.509Z","id":"5780205dd7acf5b94d9fc15a"}
```

===

Get buckets to get ID of an existing bucket.

REQ
```
2 * Client out-bound request
2 > GET https://api.storj.io/buckets
2 > Accept: application/json
2 > Authorization: basic XXXXXXXX
```

RESP
```
2 * Client in-bound response
2 < 200
2 < Server: nginx/1.10.0
2 < ETag: W/"f1-l6k7RhaR4mgC3+egjfMtzA"
2 < Access-Control-Allow-Credentials: true
2 < Connection: keep-alive
2 < Vary: Origin
2 < Content-Length: 241
2 < Date: Fri, 08 Jul 2016 21:51:25 GMT
2 < X-Powered-By: Express
2 < Content-Type: application/json; charset=utf-8
2 < 
[{"user":"steveswfc@gmail.com","created":"2016-07-01T08:41:34.184Z","name":"Test","pubkeys":["03a695035e54b565cf988ed62190d6dd093cef69e6f62e90574d90b330ba196247"],"status":"Active","transfer":30,"storage":10,"id":"57762cbe5c260bc33a6d3b4e"}]

```
====

Put a file, just with "Foo" values to see a response.

REQ
```
3 * Client out-bound request
3 > PUT https://api.storj.io/frames/5780205dd7acf5b94d9fc15a
3 > Accept: application/json
3 > Content-Type: application/json
3 > Authorization: basic XXXXXXXX
{"_id":null,"index":0,"hash":"Foo","size":3,"tree":["Foo"],"challenges":["Foo"]}
```

=== 

RESP
```
3 * Client in-bound response
3 < 502
3 < Server: nginx/1.10.0
3 < Connection: keep-alive
3 < Content-Length: 173
3 < Date: Fri, 08 Jul 2016 21:51:26 GMT
3 < Content-Type: text/html
3 < 
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
```

**Comment by bookchin** [comment]
A little context... This API request contains information (like the data hash, the challenges, and merkle tree leaves) that gets published to the network as a storage contract proposal. 

If the parameters are not valid for the protocol, then farmers will not bid on them and no one will submit an offer to the bridge, thus the request times out and the load balancer returns this error. 

Submitting "foo" for a value that farmers expect to be a 160 bit hex string will do this. We do need to handle these cases better and perform more aggressive validation before publishing contracts, but until then we can get your request formed properly.

@harryio can you provide the request for PUT /frames/{frame_id}?

**Comment by harryio** [comment]
@NutterzUK Sure mate! Here's the link for my repo: https://github.com/harryio/storj-android. However, the code for uploading files is not in there yet. I'm waiting for this issue to be resolved before it can be incorporated in the repo. Nevertheless, have a look at the repo and tell me what do you think. I would be happy to cooperate. Also, the link to your repo is dead(404 Not Found). Is there any alternate link?

@bookchin Are you suggesting that values from my api request to `/frames/{frame_id}` are incorrect that's why the farmers are not not bidding on it?

**Comment by bookchin** [comment]
@harryio that would be my guess if you consistently get this same response, though from looking at the request I don't see anything glaringly obvious. 

If I were you I'd do my testing against a locally running bridge server so you can better debug both sides.

**Comment by NutterzUK** [comment]
@harryio Sorry - yes I went through a bit of restructuring earlier and ended up making a new project. I think we are just about at the same point with it (Stuck with uploading). Here is an updated link: https://github.com/NutterzUK/storj-java-bridge-client

I think it would be really good to have a clear explanation somewhere of how the merkle tree works and with a solid example. For example:
Given 1 shard and 4 challenges, exactly how the "Tree" part of body is meant to be calculated. I am currently doing:

SHA256( SHA256 (shard) + challenge) for a single challenge, and i'm getting this 502. If I add more challenges, it gets more difficult to calculate this tree and the API example only shows a single "Tree" value (even though it's an array).

**Comment by bookchin** [comment]
Hash algorithm should be RMD160(SHA256(...)). Anywhere you are doing SHA256 needs to be changed to that. 

See the auditing section of the protocol specification: https://storj.github.io/core/tutorial-protocol-spec.html

**Comment by NutterzUK** [comment]
Thanks @bookchin.

@harryio I see we can create audits using the CLI, e.g
`"storj prepare-audits 1 <path-to-file>`"

By doing this and checking the output, it will be possible to verify that we can send the expected requests.

**Comment by bookchin** [comment]
@harryio see the #dev channel, I believe we worked this out for @nutterzuk

**Comment by NutterzUK** [comment]
We got really close. The only issue now is I can't actually create the correct "tree" from a challenge as it seems the bridge is doing some strange things (hexing after each hash, and hexing inputs etc) which make it tricky to see where my code doesn't match.

**Comment by harryio** [comment]
Finally!!! Got it working guys. @NutterzUK You were doing it correctly all this time. The only problem was that you were creating 10 challenge strings and for each challenge string, a tree value(leaf) was generated. That makes 10 elements in the tree array. But the api endpoint expects the number of tree values to be a power of 2.  See the following screen-shot of my previous conversation with Gordon. 

![image_2016-06-08_03-05-23](https://cloud.githubusercontent.com/assets/13394951/16743501/68f53194-47ca-11e6-902b-051d40b356bf.png)
 
It was also mentioned in the dev channel by James and I think you missed it.
![screenshot_20160712-005639](https://cloud.githubusercontent.com/assets/13394951/16743899/193cfcca-47cc-11e6-8858-ade63e27dfcd.png)

So, I tried the same request with 8 challenges and it worked.

Anyway, here is the request and response from my end:

**REQUEST**
```
D/OkHttp: --> PUT https://api.storj.io/frames/5783ea641ee4d5a77c706dc4 http/1.1
D/OkHttp: Content-Type: application/json; charset=UTF-8
D/OkHttp: Content-Length: 747
D/OkHttp: x-signature: 3046022100beb7428744ee3f37477fea1d36518b228f05c5b70d3a353f8f4541b19d16110c022100af6d1567559a75e7a4dc4b248253de89e5a6740af0a63ac9836c3d5eb2d1d9ce
D/OkHttp: x-pubkey: 04aca9ce9f3bb2919c5e8df1bdc30684d966bc924f7a8d1cb11935267505a32cffb22326aa491616bbe2fac7ad238158d36a5d164b6acc9b04d4e0de7acc112829
D/OkHttp: {"__nonce":1468263022505,"challenges":["e8173e6acae18267fa709a23c7eb7cb8","fa916379ad414728296170fa770a724c","e1f9888d333d70cf86c287ca2c9a4e23","165d3c7b583a15b81ee513e1d0327ce2","5a32cb7a833d8579122ee5431abdda45","1b5ad56a44d1dfe551a1477eefc78201","3de57279abd0c52c803cc6f8b9781b95","5b21e67ac45bf1c6e34c701c22f79469"],"hash":"bc1087ba27bb25f6171c3f6ad1fcb59629b81bed","index":0,"size":863792,"tree":["602ecd713d77cf1584ab89c063562a91accd0616","cb280bde78e7ca5eda3cf6da3158263b3fc2f172","67ddec2c02eef032627ec4c5fb3609a798edd01b","d4d7366ea7af1087e5bc363f7cb275ea5498a7de","07db36e4509d6be155ab47fc5ddb3bfea7fcdd71","287d234651ad59ef2f08232e87d86f087f6a814f","699a97ff913ca645ef31c82558f9402535146038","0037e6600df33c71244c67613ef2e26b89b54c46"]}
D/OkHttp: --> END PUT (747-byte body)
```

**RESPONSE**
```
D/OkHttp: <-- 200 OK https://api.storj.io/frames/5783ea641ee4d5a77c706dc4 (2695ms)
D/OkHttp: Server: nginx/1.10.0
D/OkHttp: Date: Mon, 11 Jul 2016 18:50:25 GMT
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Content-Length: 264
D/OkHttp: Connection: keep-alive
D/OkHttp: X-Powered-By: Express
D/OkHttp: Vary: Origin
D/OkHttp: Access-Control-Allow-Credentials: true
D/OkHttp: ETag: W/"108-tgisa3TFYCpMjapBm6uPWQ"
D/OkHttp: OkHttp-Sent-Millis: 1468263022609
D/OkHttp: OkHttp-Received-Millis: 1468263025258
D/OkHttp: {"hash":"bc1087ba27bb25f6171c3f6ad1fcb59629b81bed","token":"f6960272624039086b91141785dc4b84684107d7","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"5.39.79.175","port":4000,"nodeID":"b0ab82c87686f8bd26692c297b15000972a648a4","lastSeen":1468263024028}}
D/OkHttp: <-- END HTTP (264-byte body)
```

**Comment by harryio** [comment]
@bookchin So, after this I should send the json and then the shard bytes to the socket?

Also, I was watching [this] (https://www.youtube.com/watch?v=SA0lc2U05qk) video by Shawn and he explains in the 2nd step in video that if the size of the video is not the power of 2 then the file is padded with zero's to make it's size to the nearest multiple of 2. Currently I am doing no such thing and it still works. Can you explain why?

**Comment by bookchin** [comment]
The padding was removed. No need. We will work that out later.

**Comment by NutterzUK** [comment]
Oh wow! Thanks everyone, and thanks for pointing it out. I'll give this another try tonight and hopefully it's good to go!

**Comment by harryio** [comment]
@NutterzUK I already am 😜
