### ISSUE TITLE
Farmer closes connection while uploading file

### ISSUE THREAD

**Issue by harryio** [Storj/bridge#149]
Opened socket to farmer address received from a call to `/frames/{frame_id}` and sent the following json to the farmer:

```
"token": "f6960272624039086b91141785dc4b84684107d7",
"hash": "bc1087ba27bb25f6171c3f6ad1fcb59629b81bed",
"operation": "PUSH"
```
which was successfully sent to the farmer. But as soon as I try to send the shard bytes to the farmer, pipe exception occurs(farmer closes connection). I followed [this](https://storj.github.io/core/tutorial-data-channels.html) tutorial to implement this in java. I even waited for as long as 10 minutes to hear response from the farmer as mentioned in the article before sending the shard bytes to the farmer but that didn't help also.

> The receiving farmer must check that she issued the received token within a reasonable amount of time (recommend 10 minutes) and that the supplied hash is associated with that token before sending or receiving any other data.

Also, no status messages were received from the farmer.

**Comment by super3** [comment]
In some cases you will get bad farmers, this will significantly reduce as we add smarter selection. In the client there is retry logic to just try another farmer. 

So your error might be that there is incorrect communication with the farmer, or the farmer is just bad and you need to try a new one.
