### ISSUE TITLE
/buckets/{id}/files returns "name" and "filename"

### ISSUE THREAD

**Issue by NutterzUK** [Storj/bridge#158]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

api version: 0.10.0

### Expected Behavior

The response should have a filename field, not a name field as per the documentation. The documentation or implementation need updating. The response sample given on the api docs (storj.io/api) is:
`{
  "id": "507f1f77bcf86cd799439012",
  "bucket": "507f1f77bcf86cd799439011",
  "mimetype": "video/mpeg",
  "filename": "big_buck_bunny.mp4",
  "size": 5071076
}`

### Actual Behavior

Resonse contains name and filename fields:
`{"bucket":"57932e1488fc0f4839e44a49","frame":"57932e149cb11b95247cb05f","name":"cat.jpg","renewal":"2016-10-21T08:43:04.455Z","mimetype":"image/jpeg","filename":"cat.jpg","id":"57932e1888fc0f4839e44a4c","size":136356}
`

### Steps to Reproduce

1. Create a bucket.
2. Create a frame.
3. Add shards to the frame.
4. Call the buckets/{id}/frames endpoint.

**Comment by NutterzUK** [comment]
Renewal also isn't mentioned in the docs.

**Comment by bookchin** [comment]
Looks like we use a virtual property for `filename` and need to remove the actual `name` property from the response in `toObject()`: 

* https://github.com/Storj/bridge/blob/master/lib/server/routes/buckets.js#L337
* https://github.com/Storj/bridge/blob/master/lib/storage/models/bucketentry.js#L39
* https://github.com/Storj/bridge/blob/master/lib/storage/models/bucketentry.js#L49
