### ISSUE TITLE
question regarding the motivation of the bridge

### ISSUE THREAD

**Issue by jackyq2015** [Storj/bridge#164]
My understanding is that Bridge servers as a proxy to the storj network. Does that defeat the purpose of the decentralization. can a client negotiate with the farmer directly without going thought the proxy?

**Comment by bookchin** [comment]
The bridge does not necessarily proxy your connection to the storj network, but rather provides a way to interact with it using a REST API, removing the need to implement the complete protocol.

Clients still transfer data directly to and from farmers, the bridge only acts as a broker - it takes the metadata you provide it and publishes storage contracts on your behalf, then instructs clients on where to transfer data to and from. It also manages references for where your data is on the network so you can retrieve it again later. 

There can be many bridges. We run one, some community members run some, and you can run one yourself if you like or not at all - it's a convenience layer and it is not required. So no, it does not defeat the purpose of decentralization and even with the use if bridges it is still decentralized. 

Hope this answers your question.

**Comment by jackyq2015** [comment]
@bookchin Thanks for your reply. So the match between client and farmer is still dictated by bridge. And also by providing the convenience layer it will cause the inconsistency of the matching / contract  algorithm since everybody can host their own bridge. That also may lead to the unfairness IMO.

**Comment by bookchin** [comment]
The contracts are negotiated by a bridge if you choose to use a bridge, yes. But again, you don't have to use a bridge to use the network. 

I'm not sure what you mean by inconsistency/unfairness though, can you elaborate?

**Comment by jackyq2015** [comment]
If there are multiple version of bridges and even they could be running in a stealth mode, the matching algorithm could be implemented to serve the best interest of some specific group. For example, a bridge can only provide the favored farmer and exclude others from the operation level(means even open source can NOT reveal what's happening behind the scene).  I assume that all of those bridge connect to the main network and that's how the inconsistency/unfairness come from.

**Comment by bookchin** [comment]
I see. Yes, that is a plausible attack. Since bridges are federated, they do require a degree of trust when it comes to farmer selection. For instance, our bridge will ultimately perform this exact sort of "attack" but in a way that we believe to be positive - we will select farmers who send offers on contract proposals based on past performance, reputation (coming later) and other metrics.

It is up to you to decide if you wish to trust a bridge, run your own, or not use one at all.
