### ISSUE TITLE
Bridge should ignore ID attributes on POSTS to create shard.

### ISSUE THREAD

**Issue by NutterzUK** [Storj/bridge#165]
### Package Versions

 0.10.0

### Expected Behavior

Server should ignore id attribute when creating shards.

### Actual Behavior

Server sets the ID to null.

### Steps to Reproduce
`INFO: Attempting to upload shard, attempt 5 of 8
INFO: Putting shard 
8 * Client out-bound request
8 > PUT http://api.storj.io/frames/579e3ab3ee1e331f03591f84
8 > Accept: application/json
8 > Authorization: basic [REDACTED]
8 > Content-Type: application/json
{"_id":null,"index":0,"hash":"6ca40e848508518d811f29b0d69d766953733d7f","size":136356,"tree":["1d798cc02587cc45dda982e1b3586ce646cfa9dd","1645e0f39ccc38413c0b617f49ad9d3993b4cc3e","5b2fa8f6e0ff423aecdef9d24e065c012ed530d6","7e1bf8c0048d93f493b691a74f3ecb38cbecf776","58320870d995561118179174b946cb14904a306a","b6306671692a0382c32a42facc11c41a19944dd6","a764920c96c72c6476d56ec94a4123c0de30ae52","64b4964866f624629cee1ea2ba42566cb36380e4"],"challenges":["676197aa789ff75e58a8779ac01924f5","c4d3c9f77cbd3f42e347108477a3d8ac","b63a4ffab15537b18e737ded269c170c","57f4cd745cf3aeafb12925895851615c","48d7d949cd67993943da3b69fa75cf21","fbae6849e82adf3cb51ebe85e1e07298","f4cef8808cd1e35f3bfefd186b3ad1f4","1877a24acbcf95edbe5218465f6a3aa9"]}

8 * Client in-bound response
8 < 200
8 < Server: nginx/1.10.0
8 < ETag: W/"117-WMqF/hjcaEiq/ju3q56/lg"
8 < Access-Control-Allow-Credentials: true
8 < Connection: keep-alive
8 < Vary: Origin
8 < Content-Length: 279
8 < Date: Sun, 31 Jul 2016 17:52:53 GMT
8 < X-Powered-By: Express
8 < Content-Type: application/json; charset=utf-8
8 < 
{"hash":"6ca40e848508518d811f29b0d69d766953733d7f","token":"bb86c5c38d85424ff4951529b712e666c1d4f696","operation":"PUSH","farmer":{"protocol":"0.7.1","address":"STORJ-CLUS-005.storj.space","port":4000,"nodeID":"68f729b3e6b3447207e50fc8a979ec55ba00c7b4","lastSeen":1469987572875}}

9 * Client out-bound request
9 > GET http://api.storj.io/frames/579e3ab3ee1e331f03591f84
9 > Accept: application/json
9 > Authorization: basic [REDACTED]

9 * Client in-bound response
9 < 200
9 < Server: nginx/1.10.0
9 < ETag: W/"90-Q1ZCaApcaM7A1BUtBBTh+A"
9 < Access-Control-Allow-Credentials: true
9 < Connection: keep-alive
9 < Vary: Origin
9 < Content-Length: 144
9 < Date: Sun, 31 Jul 2016 17:52:54 GMT
9 < X-Powered-By: Express
9 < Content-Type: application/json; charset=utf-8
9 < 
{"user":"nutterzuk@gmail.com","shards":[null],"size":136356,"locked":false,"created":"2016-07-31T17:51:47.077Z","id":"579e3ab3ee1e331f03591f84"}`

**Comment by bookchin** [comment]
Looks like the request body just gets passed on through.
