### ISSUE TITLE
Publish reward calculation formula

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#178]
As farmer I have a few problems with the last reward calculation. I have 300GB used space but 20% contracts with unpaid bridge server. I didn't calculate the used space per renterID.

Please publish the reward caluclation. You may change the rules for the next payout. That is fine as long as you publish it and give us farmer a few days to reconfigurate our nodes. Please don't change the rules on the last day.

I would like to know the calculation formula. How many rewards do I get for 1 GB? How many rewards do I get for 100 Downloads of that one GB? Based on this information I have to decide if my node should go for api.storj.io contracts and storj.dk contracts or better block storj.dk in order to get more income.

**Comment by littleskunk** [comment]
I uploaded a few files myself and it looks like the reward payout will got to big datacenter only. Home user have a high ping and will not get many contracts even if they hold 1K SJCX. At the same time datacenter can get 5 shards from one file upload. See https://github.com/Storj/core/issues/359

**Comment by jackyq2015** [comment]
So I think how the contract is sent to farmer is also everyone concern
about especially for home  based farmers

**Comment by littleskunk** [comment]
@jackyq2015
The bridge will send the contract to the farmer nodeID that is close to the shard hash. You can see that here: https://github.com/Storj/core/issues/250#issuecomment-234928305

The problem is the contract OFFER part. See https://github.com/Storj/core/issues/359

**Comment by bookchin** [comment]
This doesn't belong here as it's unrelated to the bridge software. I'd say if you want to keep it open, move to it http://docs.storj.io/discuss
