### ISSUE TITLE
Token Expiration

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#183]
I noticed today that the https://app.storj.io/ does not have a token expiration (or if it does it is really really long). I created my bucket about a month-ish ago and when I clicked Login today it remembered me and signed right in.

I would recommend adding a Token expiration (or making it shorter if it is there) for security.

**Comment by bookchin** [comment]
The bridge-gui does not authenticate via token/session, but the same way any other services does: by using ECDSA. There is no state managed on the bridge side. If you think it's a good idea for the bridge-gui to invalidate keys after a given time, you can open an issue there.

**Comment by computeronix** [comment]
opened on bridge-gui  https://github.com/Storj/bridge-gui/issues/87
