### ISSUE TITLE
how do include in php

### ISSUE THREAD

**Issue by isaack0815** [Storj/bridge#188]
Hello, how can I create the connection with php, I can be a special surface create with php?

**Comment by super3** [comment]
@isaack0815 Here is a tutorial on uploading data to the network: [https://storj.github.io/core/tutorial-renting-data.html](https://storj.github.io/core/tutorial-renting-data.html). The protocol is language agnostic, but it will take a bit of work to get it working in PHP as we don't have a library for it yet. 

All the documentation is in the [core repository](https://storj.github.io/core/index.html), as well as a reference implementation in Javascript.

**Comment by super3** [comment]
Don't think I can provide you with detailed help via a Github issue. I'm Shawn on [our slack](https://storj.io/community.html). Ping me there and I can add you do a dedicated channel for getting Storj working in PHP.
