### ISSUE TITLE
Port 80 Public not working

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#190]
### Package Versions

```
C:\Users\storj_bridge_svc\AppData\Roaming\npm
└── storj-bridge@0.11.1
```

```
v4.5.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
When you go to your public IP/DNS name port 80 should work if configured for web communications
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Does not work but the default port 6382 works
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install bridge server (this is on a windows box)
2. My sample excerpt configuration is

  "server": {
    "host": "storj-bridge-01.storj.space",
    "port": 6382,
    "timeout": 240000,
    "ssl": {
      "cert": null,
      "key": null,
      "ca": [],
      "redirect": 80
    },
    "public": {
      "host": "storj-bridge-01.storj.space",
      "port": 80
    }
  },

6382 shows {"error":"Checksum mismatch"}

80: webpage cannot be displayed even though the port is opened.   And the port is not responding to any type of requests.

**Comment by bookchin** [comment]
You have `server.port` still set to `6382`. The `public` block is what the host tells others it's port is. This is configuring a load balancer.
