### ISSUE TITLE
Same bucket name can be created over and over

### ISSUE THREAD

**Issue by utdrmac** [Storj/bridge#197]
### Expected behavior

Attempting to create a bucket with the same name under the same user account should result in error "duplicate bucket name"

### Actual behavior / steps to reproduce

Call client.createBucket() with same parameters over and over. A new bucket is created each time with the same name. A different hash, yes, but same "user friendly" name. Could be confusing to users.

**Comment by littleskunk** [comment]
As developer I hate unique names that don't need to be unique. I would like to download a complete bucket with everything in it, modify some files and upload everything into a new bucket with the same name. I have no problems to identify the buckets by ID. I can check the complete upload of the new bucket and maybe delete or rename the old bucket (if possible).

That would allow me to implement a simple version control. The old version is still there if needed and I am not forced to add a stupid Counter for a "user frindly" name.

Lets wait for a decision :)

**Comment by bookchin** [comment]
I'm still feel pretty strongly that names should not be forced to be unique. There is no reason to create a compound index for user<->bucketname when every bucket already has a unique ID.

**Comment by utdrmac** [comment]
Alrighty. I got over-ruled. I guess this could become a client-implementation thing.
