### ISSUE TITLE
upload-file allow passthru passphrase

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#199]
Allow passthru command line passphrase

upload-file (and other commands)

**Comment by littleskunk** [comment]
You are looking for a way to skip the passphrase Input?

upload-file --keypass or Environment variable 
https://github.com/Storj/core/blob/06be816c75460373c5997a540da90b51e54db110/doc/environment-variables.md#storj_keypass

If that is not what you are looking for please open a new core issue.
