### ISSUE TITLE
directory does not exist continues anyway

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#200]
core: 3.0.4

if the directory does not exist it continues downloading anyway (not sure where though perhaps temp folder)

 [Mon Aug 29 2016 01:33:08 GMT-0400 (Eastern Daylight Time)] [info]   Creating r
etrieval token...
 [Mon Aug 29 2016 01:33:08 GMT-0400 (Eastern Daylight Time)] [error]  ENOENT: no
 such file or directory, open 'C:\storj\downloads\test\file.txt'
 [Mon Aug 29 2016 01:33:09 GMT-0400 (Eastern Daylight Time)] [info]   Resolving
6 file pointers...
 [Mon Aug 29 2016 01:33:14 GMT-0400 (Eastern Daylight Time)] [info]   Creating r
etrieval token...
 [Mon Aug 29 2016 01:33:14 GMT-0400 (Eastern Daylight Time)] [info]   Resolving
6 file pointers...
 [Mon Aug 29 2016 01:33:15 GMT-0400 (Eastern Daylight Time)] [info]   Received 1
8542 of 18542 bytes

**Comment by littleskunk** [comment]
Moved to https://github.com/Storj/core/issues/371
