### ISSUE TITLE
cause bridge to error instead of invalid email

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#204]
https://github.com/Storj/core/issues/381

Can cause the bridge to issue error [minor security hole] if you do the following (overflow the variable)

storj register

for email enter
abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123@abc.com

password: b

[Mon Aug 29 2016 22:31:02 GMT-0400 (Eastern Daylight Time)] [error] WiredTigerIndex::insert: key too large to index, f
ailing 1100 { : "abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123
abc123abc123abc123abc123abc123abc123abc123abc123..." }

**Comment by computeronix** [comment]
Debug Logs:

C:\Windows\system32>storj register -d
 [...]  > Enter your email address  >  abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc1
23abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc12
3abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123
abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123a
bc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123ab
c123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc
123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc1
23abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc12
3abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123
abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123@abc.com
 [...]  > Enter your password  >  *

 [Tue Aug 30 2016 15:13:53 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.storj.io","u
ri":"/users","method":"POST","json":{"email":"abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc
123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc1
23abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc12
3abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123
abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123a
bc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123ab
c123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc
123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc1
23abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc12
3abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123@abc.com","password":"e3
b98a4da31a127d4bde6e43033f66ba274cab0eb7eb1c70ec41402bf6273dd8","__nonce":"339e2a83-3eff-4b29-9242-6a801ea02e49"}}
 [Tue Aug 30 2016 15:13:53 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"error":"WiredTigerIndex::insert: key
too large to index, failing  1100 { : \"abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc
123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123...\" }"}
 [Tue Aug 30 2016 15:13:53 GMT-0400 (Eastern Daylight Time)] [error]  WiredTigerIndex::insert: key too large to ind
ex, failing  1100 { : "abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc123ab
c123abc123abc123abc123abc123abc123abc123abc123abc123abc123..." }

**Comment by bookchin** [comment]
While the error message could be made nicer, I don't think it's worth writing the code to satisfy intentional garbage input. As far as security is concerned, I don't see how this might pose any threat.
