### ISSUE TITLE
storj create-mirrors cast to object failure

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#205]
Referencing https://github.com/Storj/core/issues/382

### Package Versions

```
storj@3.0.1
```

```
v4.5.0
```

### Expected Behavior

```
storj list-files 57c3a9f281e21cfd4f3d97*3f

should error out saying invalid bucket
```

### Actual Behavior

```
storj list-files 57c3a9f281e21cfd4f3d97*3f

 [Mon Aug 29 2016 23:36:47 GMT-0400 (Eastern Daylight Time)] [error]  Cast to ObjectId failed for value "57c3a9f281e21cf
d4f3d97*3f" at path "_id"
```

### Steps to Reproduce

1. storj list-files 57c3a9f281e21cfd4f3d97*3f

**Comment by computeronix** [comment]
Debug logs:

C:\Windows\system32>storj list-files 57c3a9f281e21cfd4f3d97*3f -d
 [Tue Aug 30 2016 15:12:49 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.storj.io","u
ri":"/buckets/57c3a9f281e21cfd4f3d97*3f/files","method":"GET","qs":{"__nonce":"d3fe176f-233f-4ad7-90b2-3dea20b9a2cb
"},"json":true,"headers":{"x-pubkey":"036ee38f5f8cb79efd07a993a32a6e1a2693bc728b41c486664eb7464d7cbcaa54","x-signat
ure":"3045022027b22d15ae9a232aa82e2f29da6fa57506376fb28e4c5a0663b42443f0a395c4022100b9c96d7c664742fba92ffd7320d5ebd
e2fdff8107b562926914e92c4c7ba7857"}}
 [Tue Aug 30 2016 15:12:49 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"error":"Cast to ObjectId failed for v
alue \"57c3a9f281e21cfd4f3d97*3f\" at path \"_id\""}
 [Tue Aug 30 2016 15:12:49 GMT-0400 (Eastern Daylight Time)] [error]  Cast to ObjectId failed for value "57c3a9f281
e21cfd4f3d97*3f" at path "_id"

**Comment by bookchin** [comment]
This is expected behavior. You provided an invalid ObjectId and the bridge couldn't cast it to the correct type.
