### ISSUE TITLE
unlimited size or null size buckets

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#206]
Referencing: https://github.com/Storj/core/issues/383

run the command 
`
storj add-bucket "Name" 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
`

it then shows

 [Tue Aug 30 2016 00:07:58 GMT-0400 (Eastern Daylight Time)] [info]   ID: 57c5069e43790f5527db306b, Name: Name, Storage:
 null, Transfer: null

**Comment by computeronix** [comment]
Debug Logs:

C:\Windows\system32> storj add-bucket "Name" 9999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999 99999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999 -d
 [Tue Aug 30 2016 15:10:55 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.storj.io","u
ri":"/buckets","method":"POST","json":{"name":"Name","storage":"999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999","transfer":"999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999","__nonce":"465f79be-41b3-44fd-b2f2-064b83e1fbf9"},"headers":{"x-pubkey":"036ee38f5f8cb79efd07a993a32a6e1a2693bc728b41c48
6664eb7464d7cbcaa54","x-signature":"304502210088370a6d3429b6670bdf5d3eb51c84143ec737ffd4753436489f12edaf5f2e1502203
71d813ed140a9fa6a6798d132e193014c978f4eedf2cc6658eab32550afe556"}}
 [Tue Aug 30 2016 15:10:55 GMT-0400 (Eastern Daylight Time)] [debug]  Body: {"user":"bill@storj.io","created":"2016-08-30T19:10:56.229Z","name":"Name","pubkeys":["036ee38f5f8cb79efd07a993a32a6e1a2693bc728b41c486664eb7464d7cbcaa54"],"status":"Active","transfer":null,"storage":null,"id":"57c5da40f0ea649f5e611aa2"}
 [Tue Aug 30 2016 15:10:55 GMT-0400 (Eastern Daylight Time)] [info]   ID: 57c5da40f0ea649f5e611aa2, Name: Name, Storage: null, Transfer: null

**Comment by bookchin** [comment]
https://github.com/Storj/bridge/issues/147
