### ISSUE TITLE
vulnerability: allow weird character in buckets

### ISSUE THREAD

**Issue by computeronix** [Storj/bridge#207]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
3.1.0
```
```
v4.5.0
```

### Expected Behavior

```
bucket id should error out when invalid
```

### Actual Behavior

```
application allows you to escape bucket id potentially allowing a slew of other commands to work

again it would have to be coded right and tricky to do but the opening is there
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1.storj list-files \
2.storj list-files /

Log

PS C:\Users\storj_cli> storj list-files \ -d
 [Tue Aug 30 2016 16:26:42 GMT-0400 (Eastern Daylight Time)] [debug]  Request: {"baseUrl":"https://api.storj.io","uri":"
/buckets/\\/files","method":"GET","qs":{"__nonce":"db27dabf-81b2-40c6-a38e-6fbd8336e580"},"json":true,"headers":{"x-pubk
ey":"036ee38f5f8cb79efd07a993a32a6e1a2693bc728b41c486664eb7464d7cbcaa54","x-signature":"304502203bae42751d54c1a7d8e09be0
246244058984814e1f2c059bee606c93fce6e99002210094ce6a0efcbb9a6ae5de26be671b00ae0041268d9e5e2418131980680022bbc4"}}
 [Tue Aug 30 2016 16:26:42 GMT-0400 (Eastern Daylight Time)] [debug]  Body: "Cannot GET /buckets///files?__nonce=db27dab
f-81b2-40c6-a38e-6fbd8336e580\n"
 [Tue Aug 30 2016 16:26:42 GMT-0400 (Eastern Daylight Time)] [error]  Cannot GET /buckets///files?__nonce=db27dabf-81b2-
40c6-a38e-6fbd8336e580

**Comment by bookchin** [comment]
I don't see any vulnerability here. The request router on the bridge will not evaluate any code embedded into the url path.

**Comment by computeronix** [comment]
hey gordon!   the only reason it would be a low vulnerability would be because putting a “weird” character exposes code unintentionally     from there you can manipulate the code through the storj client
