### ISSUE TITLE
Bridge API is ambiguous

### ISSUE THREAD

**Issue by virl** [Storj/bridge#221]
Bridge API is ambiguous (https://storj.io/api.html):
1. Body and response schema have all parameters as "optional" — why?? Are they're REALLY optional?
1. No status codes descriptions on most of the methods. And where there ARE status codes, they're not consistent with others.

**Comment by braydonf** [comment]
Please see code for more specific details:
- https://github.com/Storj/bridge/tree/master/lib/server/routes
- https://github.com/Storj/service-error-types
