### ISSUE TITLE
Make it clearer when setting a passphrase for the keyring 

### ISSUE THREAD

**Issue by conorohiggins** [Storj/bridge#227]
When uploading the first file with a new account, there is a prompt 'Enter your passphrase to unlock your keyring'. 

This is a bit misleading: the passphrase does not exist at that point. The prompt should say, 'Create a passphrase for your keyring', or something like that. 

Also, when creating a passphrase, it's good practice to prompt for it to be entered twice in case of typos

**Comment by bookchin** [comment]
this belongs in core-cli
