### ISSUE TITLE
Hash returns empty - "List the all the file metadata stored in the bucket"

### ISSUE THREAD

**Issue by tempestb** [Storj/bridge#241]
Using api.storj.io doing JSON calls via external application (No CLI)
### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

In reference to /buckets/{id}/files

This call should return...

[
  {
    "hash": "9c1185a5c5e9fc54612808977ee8f548b2258d31",
    "bucket": "507f1f77bcf86cd799439011",
    "mimetype": "video/mpeg",
    "filename": "big_buck_bunny.mp4",
    "size": 5071076
  }
]
### Actual Behavior

It is returning...

[
  {
    "hash": "",
    "bucket": "507f1f77bcf86cd799439011",
    "mimetype": "video/mpeg",
    "filename": "big_buck_bunny.mp4",
    "size": 5071076
  }
]
### Steps to Reproduce
1. Upload a file with the CLI.
2. Use method above to get JSON response.
3. Observe that Hash is empty.
4. Consider Seppeku as possible solution rather than fixing the problem.

Seriously though, I am getting all the other results fine, but the hash appears to be empty.  Was assuming that the Hash is the unique identifier to the file.  So without it, would probably need to use the filename as the unique which could become problematic in blind uploads.

**Comment by bookchin** [comment]
I'd hold off on unsheathing your sword, this is likely just a bug in the request handler - files are given a unique ID and the hash is stored as well.
