### ISSUE TITLE
Bridge seed information missing

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#244]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
"version":"1.0.2","description":"Access the Storj network using a simple REST API.","x-protocol-version":"0.9.0","x-core-version":"4.0.1"
```

Replace the values below using the output from `node --version`.

```
None
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

The old bridge version displayed all minion seeds on api.storj.io  That information allows farmer to connect to the bridge.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

seed information are missing on api.storj.io Not one farmer is able to connect.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by bookchin** [comment]
This is no longer supported in the new bridge. The `storj-lib` package has been updated to use `/contacts`
