### ISSUE TITLE
Features for Mirroring and Downloading

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#246]
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```
### Expected Behavior
- Allow mirroring of all files inside a buckets at once.
- Allow the user to check how many mirrors have been created for a specific file.
- Inform the user at mirroring how many mirrors have already been created and how many can still be created
- If no more mirrors can be created for a file the user is informed on this matter.
 - Allow a user to download all the files inside a bucket at once.
### Actual Behavior
- We can only mirror one file at a time.
- A user does not know if the file is already mirrored or not, and how many mirrors are currently in circulation for that specific file.
- Currently a user wanting to download all the files inside a specific bucket has to download all files one-by-one. This can be achieved by for example: `storj upload-file <Bucket ID> /*`   , `/*` meaning all files. The same would apply to mirroring all files inside of a bucket.

**Comment by lakewik** [comment]
I also would like to be able to view a list of mirrors

**Comment by bookchin** [comment]
* [ ] ~Allow mirroring of all files inside a buckets at once.~
  * *Up to implementing clients - no need to provide a separate endpoint on bridge for this*
* [ ] Allow the user to check how many mirrors have been created for a specific file.
  * *Yes - will implement*
* [ ] Inform the user at mirroring how many mirrors have already been created and how many can still be created
  * *Yes - will implement*
* [ ] If no more mirrors can be created for a file the user is informed on this matter.
  * *Yes - will implement*
* [ ] ~Allow a user to download all the files inside a bucket at once.~
  * *Up to implementing clients - no need to provide a separate endpoint on bridge for this*

**Comment by bookchin** [comment]
Also...

* I'm implementing automatic replication, so you won't have to specify the number of mirrors to get enough for sufficient durability. 
* You'll be able to list the mirrors established (`GET /buckets/{bucketid}/files/{fileid}/mirrors`)
* Failed downloads/token retrieval will automatically establish a mirror
