### ISSUE TITLE
Upload routinely fails with retry timeout

### ISSUE THREAD

**Issue by 1credit** [Storj/bridge#248]
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
npm -list -g storj
/usr/lib64
storj@4.0.1

storj --version
Storjcli:  1.0.11 | Core:  4.0.2
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```
### Expected Behavior

Upload to succeed.

```

```
### Actual Behavior

 storj upload-file -c 1 -r 1 57b51555af035fde12cf7f5b /home/fspoe.junk , where fspoe.junk is a 2GB file, tries... it really does.  The file is split into 26 shards and it manages to upload most, but sometime before finishing, it eventually dies after retrying for a contract.  Example below shows it struggling, but succeeding after retry #10, a success after retry #4, then a timeout and abort:

 [Thu Oct 13 2016 10:12:06 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 1)
 [Thu Oct 13 2016 10:12:09 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 2)
 [Thu Oct 13 2016 10:12:12 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 3)
 [Thu Oct 13 2016 10:12:15 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 4)
 [Thu Oct 13 2016 10:12:18 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 5)
 [Thu Oct 13 2016 10:12:21 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 6)
 [Thu Oct 13 2016 10:12:24 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 7)
 [Thu Oct 13 2016 10:12:27 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 8)
 [Thu Oct 13 2016 10:12:30 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 9)
 [Thu Oct 13 2016 10:12:33 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 10)
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","address":"138.201.13.159","port":4054,"nodeID":"07a2e02adae4207d6d8c9c42ce9e3fba","lastSeen":1476371555092}
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 138.201.13.159:4054
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [info]   Retrying shard transfer, pointer: {"hash":"0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456","token":"9f0c652fe2052d50b559e411c33f6b73","operation":"PUSH","farmer":{"userAgent":"4.0.2","protocol":"0.9.0","address":"138.201.13.159","port":4054,"nodeID":"07a2e02a766abd4ddae4207d6d8c9c42ce9e3fba","lastSeen":55092}}
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [warn]   Failed to transfer shard, reason: connect ECONNREFUSED 138.201.13.159:4054
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [info]   Shard transfer failed 1 times, getting another contract...
 [Thu Oct 13 2016 10:12:35 GMT-0500 (CDT)] [info]   Hash for this shard is: 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456
 [Thu Oct 13 2016 10:12:36 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Thu Oct 13 2016 10:12:36 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Thu Oct 13 2016 10:12:36 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 0)
 [Thu Oct 13 2016 10:12:39 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 1)
 [Thu Oct 13 2016 10:12:42 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 2)
 [Thu Oct 13 2016 10:12:45 GMT-0500 (CDT)] [info]   Querying bridge for contract for 0f2dd49dcc0b7ef4a9e07aab91c19241ba2e4456 (retry: 3)
 [Thu Oct 13 2016 10:12:47 GMT-0500 (CDT)] [info]   Contract negotiated with: {"userAgent":"4.0.2","protocol":"0.9.0","address":"50.171.239.236","port":7646,"nodeID":"1b28ede37fd78de3cc119524eae25edf","lastSeen":1476371566758}
 [Thu Oct 13 2016 10:12:47 GMT-0500 (CDT)] [info]   Data channel opened, transferring shard...
 [Thu Oct 13 2016 10:14:17 GMT-0500 (CDT)] [info]   Shard transfer completed! 11 remaining...
 [Thu Oct 13 2016 10:14:17 GMT-0500 (CDT)] [info]   Trying to upload shard /tmp/6462cd69e386 index 21
 [Thu Oct 13 2016 10:14:17 GMT-0500 (CDT)] [info]   Hash for this shard is: 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059
 [Thu Oct 13 2016 10:14:18 GMT-0500 (CDT)] [info]   Audit generation for shard done.
 [Thu Oct 13 2016 10:14:18 GMT-0500 (CDT)] [info]   Waiting on a storage offer from the network...
 [Thu Oct 13 2016 10:14:18 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 0)
 [Thu Oct 13 2016 10:14:21 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 1)
 [Thu Oct 13 2016 10:14:24 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 2)
 [Thu Oct 13 2016 10:14:27 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 3)
 [Thu Oct 13 2016 10:14:30 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 4)
 [Thu Oct 13 2016 10:14:33 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 5)
 [Thu Oct 13 2016 10:14:36 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 6)
 [Thu Oct 13 2016 10:14:39 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 7)
 [Thu Oct 13 2016 10:14:42 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 8)
 [Thu Oct 13 2016 10:14:45 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 9)
 [Thu Oct 13 2016 10:14:48 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 10)
 [Thu Oct 13 2016 10:14:51 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 11)
 [Thu Oct 13 2016 10:14:54 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 12)
 [Thu Oct 13 2016 10:14:57 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 13)
 [Thu Oct 13 2016 10:15:00 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 14)
 [Thu Oct 13 2016 10:15:03 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 15)
 [Thu Oct 13 2016 10:15:06 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 16)
 [Thu Oct 13 2016 10:15:09 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 17)
 [Thu Oct 13 2016 10:15:12 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 18)
 [Thu Oct 13 2016 10:15:15 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 19)
 [Thu Oct 13 2016 10:15:18 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 20)
 [Thu Oct 13 2016 10:15:21 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 21)
 [Thu Oct 13 2016 10:15:24 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 22)
 [Thu Oct 13 2016 10:15:27 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 23)
 [Thu Oct 13 2016 10:15:30 GMT-0500 (CDT)] [info]   Querying bridge for contract for 4d7536a5bc537185ae3e0ebb9f65791e4e2bc059 (retry: 24)
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [warn]   Failed to upload shard...
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [warn]   [ fspoe.junk ] Error occurred. Triggering cleanup...
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [info]   [ fspoe.junk ] Cleaning up...
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [info]   [ fspoe.junk ] Finished cleaning!
 [Thu Oct 13 2016 10:15:33 GMT-0500 (CDT)] [error]  ETIMEDOUT

Note:  Various combinations of -r and -c  have been tried, including the defaults, -c3 -r 12, and for this example, -c 1 -r 1.

```

```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. ...
2. ...
3. ...

**Comment by littleskunk** [comment]
@1credit could be duplicate to https://github.com/Storj/core/issues/469
Do you agree?

**Comment by 1credit** [comment]
Perhaps the same core cause, but the symptoms are different.  FYI - still happening as of core 4.0.4. 

Yeah, 25 timeouts (since it starts counting at 0), each within a few seconds of each other, seems odd.  Having watched these run for a few hours, it appears to really be a crap shoot - sometimes I see 3-5 timeouts and it works, sometimes 9ish, sometimes 21, but sooner or later the magic number is hit and it crashes.  Terribly inefficient usage of bandwidth too - I can spend more time timing out than in transferring data.

**Comment by littleskunk** [comment]
@1credit Maybe this one is better: https://github.com/Storj/core/issues/517

**Comment by 1credit** [comment]
If there is some internal blacklist activity going I suppose that is possible.  I'm not manually doing anything like that.

**Comment by littleskunk** [comment]
Yes there is an internal blacklist. If you can't upload a shard you will blacklist that farmer for a few hours.

Issue should be fixed with the latest core release. We have to wait for the bridge update (core 4.0.5)

**Comment by CJClaude** [comment]
Problem still exist as of 10/17/2016:

fspoe ~ # storj --version
Storjcli: 1.0.11 | Core: 4.0.6

[Mon Oct 17 2016 16:13:35 GMT-0500 (CDT)] [info]   Querying bridge for contract for d5a2d21aee04de535cd88eb1189f4cf05ff01b40 (retry: 23)
 [Mon Oct 17 2016 16:13:38 GMT-0500 (CDT)] [info]   Querying bridge for contract for d5a2d21aee04de535cd88eb1189f4cf05ff01b40 (retry: 24)
 [Mon Oct 17 2016 16:13:41 GMT-0500 (CDT)] [warn]   Failed to upload shard...
 [Mon Oct 17 2016 16:13:41 GMT-0500 (CDT)] [warn]   [ fspoe.junk ] Error occurred. Triggering cleanup...
 [Mon Oct 17 2016 16:13:41 GMT-0500 (CDT)] [info]   [ fspoe.junk ] Cleaning up...
 [Mon Oct 17 2016 16:13:42 GMT-0500 (CDT)] [info]   [ fspoe.junk ] Finished cleaning!
 [Mon Oct 17 2016 16:13:42 GMT-0500 (CDT)] [error]  ETIMEDOUT

**Comment by littleskunk** [comment]
My farmer is sending OFFER but 20% will timeout. No bridge response.
OFFER: 40
Locked: 9
Failed: 23
Timeouts: 8

**Comment by littleskunk** [comment]
I did some more tests. Even tiny  uploads with no blacklist are getting more and more timeouts over time. -> https://github.com/Storj/core/issues/528

**Comment by CJClaude** [comment]
I started a loop last night on a 12GB file.  By morning, roughly 8 hours later, 4 of 7 passes had succeeded.  I allowed them to continue and had close to 100% failure during the day (loop was up to pass 118 in around 9.5 hours)

**Comment by littleskunk** [comment]
Found 2 bugs in kad-quasar. The bridge has problems to receive OFFER because the contract is not published correct.

Farmer should relay the contract to 3 neighbors but most of the time they relay it only to 1 and sometimes to no neighbor. Dead end after only 4 hops. I would expect only 15-45 OFFER messages. 
https://github.com/kadtools/kad-quasar/issues/16

Farmer not interested in that opcode will always relay it to only 1 node. It should be one random node but that part is not working correct. This should not be a problem at the moment because we have only 3 opcodes and by default everyone is interested.
https://github.com/kadtools/kad-quasar/issues/15

**Comment by bookchin** [comment]
1. This now belongs in complex
2. It should be resolved with upcoming release - closing here
