### ISSUE TITLE
Bucket Routes tests not passing

### ISSUE THREAD

**Issue by braydonf** [Storj/bridge#250]
On the master branch at https://github.com/Storj/bridge/commit/4461a7639830ee8b73bcac848720569c81952e0e the tests are not passing in https://github.com/Storj/bridge/blob/master/test/routes/buckets.unit.js

Error while running locally, with error in the before all hook:
```
Uncaught Error: connect ECONNREFUSED 127.0.0.1:27017
```

Build failure on travis:

```
 1) BucketRoutes #getFileInfo should return bucket information to res:
     Uncaught AssertionError: expected { Object (_id, __v, ...) } to equal 'test.txt'
      at Test.<anonymous> (test/routes/buckets.unit.js:111:36)
      at Test.assert (node_modules/supertest/lib/test.js:161:6)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1521:8)
```
https://travis-ci.org/Storj/bridge/builds/167721489

**Comment by bookchin** [comment]
The first one looks like you aren't running `mongod`. The second one is definitely broken.

**Comment by braydonf** [comment]
Yeah, just started mongod locally, and got the same error as travis.

**Comment by braydonf** [comment]
Unit tests should probably not depend on mongod running.

**Comment by bookchin** [comment]
I wonder why master is passing with that commit. :confused:

**Comment by braydonf** [comment]
Just restarted the latest build, and it's failing:
```
 1) BucketRoutes "before all" hook:

     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by braydonf** [comment]
Restarted the travis build again for master for that commit, and it's showing the same error:
https://travis-ci.org/Storj/bridge/builds/167084555

**Comment by bookchin** [comment]
:mega: paging @cpollard1001

**Comment by cpollard1001** [comment]
I made the mistake of making the new bucketEntry.create to take filename instead of name as an argument so line 59 is failing. https://github.com/Storj/bridge/blob/master/test/routes/buckets.unit.js#L59

The best way to fix this would be to merge in this bug fix in service-storage-models and then depend on that new version.

https://github.com/Storj/service-storage-models/pull/12/files

**Comment by bookchin** [comment]
New version of `storj-service-storage-models` published.

**Comment by bookchin** [comment]
Okay back in business: https://travis-ci.org/Storj/bridge/builds/167084555
