### ISSUE TITLE
ETIMEDOUT when 'storj list-files' is called of a bucket containing a very large number of files.

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#259]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@1.1.1 /home/gordon/Code/storj-bridge
└── storj@4.1.0  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.6.0
```
### Expected Behavior

when executing the command `storj list-files <bucket-ID>` a list of all files inside of the buckets is returned. 
### Actual Behavior

When uploading hundreds of thousands of files to a single bucket over the coarse of a month or two the list of files inside of that bucket becomes so large that if a user tries to return the list of files inside of that bucket using core-CLI, the call timeouts every single time. Doing the same call for smaller buckets almost immediately returns the list files inside of that bucket. So either the bridge or the core-CLI is having trouble processing and returning the list of files in time.

```
C:\Users\Dani Marion>storj list-files 57af3a1e8f266a7d4e391055
 [Sat Oct 22 2016 14:20:02 GMT+0200 (W. Europe Daylight Time)] [error]  ETIMEDOUT
```
### Steps to Reproduce
1. Upload hundreds of thousands of files to a single bucket
2. ask Core-CLI to return all files inside of the bucket
3. TIMEDOUT

Cheers.

**Comment by bookchin** [comment]
Related to #237
