### ISSUE TITLE
Testing network/bridge needed.

### ISSUE THREAD

**Issue by F483** [Storj/bridge#267]
In order to test the storj-python-sdk properly I must make calls to an actual bridge instance, otherwise the "tests" are essentially worthless.

The main problem stopping me from doing this is the email loop, having a testing only method of looking up the tokens sent to email would be needed.

Doing so on the main bridge is probably a very bad idea ... on staging also as its job is to mimic the main bridge before deployment. Was is needed is a testing only bridge with some additional api call to retrieve sent tokens.

**Comment by braydonf** [comment]
Please see https://github.com/Storj/integration that can be tested against.
