### ISSUE TITLE
What calls are authenticated?

### ISSUE THREAD

**Issue by F483** [Storj/bridge#268]
I assumed the [authentication middleware](https://github.com/Storj/service-middleware/blob/master/lib/authenticate.js) would be used globally, but this seems to not be the case as the following call worked fine without any errors.

```
REQUEST: {                                                                     
  "method": "GET",                                                             
  "data": "null",                                                              
  "params": {},                                                                
  "headers": {                                                                 
    "x-signature": "invalid",                                                  
    "x-pubkey": "03395a476caf8116ac28963f6582c79e8fa1fdc2ca16ab08fb88da17760ab45b6b"
  },                                                                           
  "url": "https://api.storj.io/contacts"                                       
}  
```

What calls require authentication and could this be added to the [documentation](https://storj.io/api.html)?

**Comment by braydonf** [comment]
All endpoints with the exception of `/` and exchange reports are authenticated. The only endpoint that currently uses a token for authentication is for file pointers at `/buckets/<bucket-id>/files/<file-id>`.
