### ISSUE TITLE
Bridge does not return the name of the files in the bucket anymore

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#283]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@2.1.0 /home/gordon/Code/storj-bridge
└── storj@5.1.0 -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Bridge returns the name of the file.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Bridge does not return the name of the files anymore.

C:\Users\Dani Marion>storj list-files 994ee4759cfc6292f7f5dde3
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
 [Mon Nov 14 2016 18:41:17 GMT+0100 (W. Europe Standard Time)] [info]   Name: [object Object], Type: video/mp4, Size: 763809061 bytes, ID: 7
fd4845122ccf732d6aba13a
 [Mon Nov 14 2016 18:41:17 GMT+0100 (W. Europe Standard Time)] [info]   Name: [object Object], Type: video/mp4, Size: 864472357 bytes, ID: c
2201bf467b8a3a28265d0d2

C:\Users\Dani Marion>
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. upload a file to bucket
2. list files in bucket.
3. ...

**Comment by bookchin** [comment]
@braydonf

**Comment by bookchin** [comment]
Ooh! Found it. Fix incoming.

**Comment by bookchin** [comment]
https://github.com/Storj/service-storage-models/releases/tag/v5.0.3
