### ISSUE TITLE
Upload returning wrong file name.

### ISSUE THREAD

**Issue by tempestb** [Storj/bridge#284]
### Package Versions

I'm doing calls to the Bridge outside of NPM.

POST to buckets/{id}/files

Which is "Store a file in the Storj network through Storj Bridge"

If you do this, it is supposed to return... 

{
  "id": "507f1f77bcf86cd799439012",
  "bucket": "507f1f77bcf86cd799439011",
  "mimetype": "video/mpeg",
  "filename": "big_buck_bunny.mp4",
  "size": 5071076
}

However, it is returning...

{
  "id": "54e7dca23ed1ef63e14b4ed9",  <--  No idea what this is.   It's supposed to be the auth frame id. 
  "bucket": "507f1f77bcf86cd799439011",  <--  Bucket is correct.
  "mimetype": "video/mpeg",  <--  Correct.
  "filename": "507f1f77bcf86cd799439012"   <-- This is the auth frame id.
  "size": 5071076  <-- Correct.
}

Same behavior exists when running in the CLI.   

If the output has changed on purpose, that's fine, but it is not updated in the API documentation as far as I can tell.

**Comment by bookchin** [comment]
Fixed in https://github.com/Storj/service-storage-models/releases/tag/v5.0.3
