### ISSUE TITLE
Limits for the total number of buckets and files within a bucket

### ISSUE THREAD

**Issue by vevarm** [Storj/bridge#293]
### Package Versions

v6.9.1
Storjcli: 2.0.1 | Core: 5.1.2
 [Sat Nov 19 2016 20:56:02 GMT+0100 (CET)] [info]   Title:             Storj Bridge
 [Sat Nov 19 2016 20:56:02 GMT+0100 (CET)] [info]   Description:       Access the Storj network using a simple REST API.
 [Sat Nov 19 2016 20:56:02 GMT+0100 (CET)] [info]   Version:           2.2.3
 [Sat Nov 19 2016 20:56:02 GMT+0100 (CET)] [info]   Host:              0.0.0.0

### Expected Behavior

Buckets are listed OR error message "you are stupid for have created so many buckets"

### Actual Behavior

ESOCKETTIMEDOUT

### Steps to Reproduce

1. Create stupid many bucket on your account like 50K or so buckets
2. Try to list them
3. ...

**Comment by vevarm** [comment]
list-keys also suffer from this.

**Comment by vevarm** [comment]
list-frames too

**Comment by vevarm** [comment]
generealized the title

**Comment by braydonf** [comment]
On the creation side of this, we should have some rate limits. The listing side of this will be resolved with https://github.com/Storj/bridge/pull/384 where a startDate can be used to query buckets and bucket entries.
