### ISSUE TITLE
API lacks protection from abuse

### ISSUE THREAD

**Issue by vevarm** [Storj/bridge#296]
### Package Versions

```
 [Fri Nov 25 2016 06:54:18 GMT+0100 (CET)] [info]   Title:             Storj Bridge
 [Fri Nov 25 2016 06:54:18 GMT+0100 (CET)] [info]   Description:       Access the Storj network using a simple REST API.
 [Fri Nov 25 2016 06:54:18 GMT+0100 (CET)] [info]   Version:           2.2.4
```

### Expected Behavior
If you query the brigde too hard you should get a "back off dude" error message, if still persisting it would be a useful to get temporary FW blocked. 

It is currently too easy to intensionally or unintentionally overload the api. 
Especially list-files and list-buckets are very expensive calls on bridge when many items exists. In it current state  1 call per minute can overload the system using these calls with sufficiently many files/buckets. 

### Actual Behavior

So far I have never been asked to back off. I think at times I have queried api harder than what makes complete sense. 

```

```

### Steps to Reproduce

This is more of review activity do you have api abuse protection or not.

**Comment by subwolf** [comment]
https://github.com/chilts/oibackoff could help?

**Comment by dylanlott** [comment]
Taking a break off this to get billing and referrals into production. Will resume this after referrals is in production ~ the 15th of February.

**Comment by braydonf** [comment]
When looking at https://github.com/Storj/bridge/issues/293 to add limits on the total number of buckets and bucket entries that can be created, I think it makes more sense to have a small cost for each bucket and bucket entry.

**Comment by dylanlott** [comment]
Closing as per #401
