### ISSUE TITLE
Incorrect size on frame recorded

### ISSUE THREAD

**Issue by braydonf** [Storj/bridge#305]
### Package Versions

```
storj-bridge@3.1.1
```

### Expected Behavior

Correct size of the file to be recorded

### Actual Behavior

Incorrect size of file being recorded. The behavior is somewhat unpredictable, however has happened twice to me now. The first time, with a small file, the total size was exactly equal to twice the one and only shard size.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Upload a file from using storj-cli
2. After successful PUSH token to upload data, introduce (or encounter) an error during upload to farmer, and retry the upload again (storj-cli will do this automatically).
3. Attempt to download the file, and it will endlessly wait for more data...

It's possible that the size is being double incremented at:
https://github.com/Storj/bridge/blob/master/lib/server/routes/frames.js#L175
```js
}).populate('shards').exec(function(err, frame) {
  if (err) {
    return next(new errors.InternalError(err.message));
  }

  for (let i = 0; i < frame.shards.length; i++) {
    if (frame.shards[i].index === req.body.index) {
      frame.shards.splice(i, 1);
      break;
    }
  }

  frame.size += pointer.size; <--- here
```

**Comment by littleskunk** [comment]
I noticed this issue as well but didn't create an issue. Each upload retry will incremtend the file size even if the upload failes.

**Comment by braydonf** [comment]
Same here, until running into the issue again today.

It's fixed with https://github.com/Storj/bridge/pull/307
