### ISSUE TITLE
Bridge operators have complete access to file metadata

### ISSUE THREAD

**Issue by utdrmac** [Storj/bridge#321]
This is a huge security issue. This information is available as plain, unencrypted data, to any bridge operator. We, clients and farmers, are supposed to put our trust in the network that our data is safe and secure against invasion and detection.

This is not the case. Any bridge operator can easily log in to mongo and run a basic query to see file names, types and sizes.

This information needs to be secured with the uploaders key so that it is only accessible by the original data owner.

```
> db.bucketentries.find().limit(1).pretty()
{
	"_id" : ObjectId("30edc2e708440222ac62029a"),
	"bucket" : ObjectId("4745cc69022a15045cb22590"),
	"__v" : 0,
	"renewal" : ISODate("2017-04-02T21:17:11.811Z"),
	"created" : ISODate("2017-01-02T21:17:11.811Z"),
	"frame" : ObjectId("586ac0a797ecf163e7053838"),
	"name" : "100mb.dat",
	"mimetype" : "application/octet-stream"
}
```

**Comment by utdrmac** [comment]
I'll reference bullet point #5 on the master plan: http://blog.storj.io/post/151390093908/storj-master-plan

> Better privacy - Storj operates a zero-knowledge system which does not need to know anything about the data stored on the network in order to be able to operate. This means the USER’s data stays private, and properly built applications can take advantage of this as well.

**Comment by braydonf** [comment]
I don't think this is a bridge issue, as the client is what is giving it the name. If the name should be encrypted, then this would need to be done with the client that is sending the filename.

**Comment by lunokhod** [comment]
This is a huge security issue, regardless of whether if falls under then domain of `bridge` or `client`. 

Let me quote from Wilkinson and Lowry (2014):

> We need a cloud storage model that is not based on trust between client and
host. All client private data, including filename, date and other metadata, must
be encrypted before any transfer takes place from a clients computer to the
cloud.

The current configuration does not achieve this goal.

**Comment by utdrmac** [comment]
This is a bridge issue as the bridge is storing this information. The bridge retrieves this info itself from mongo.

**Comment by utdrmac** [comment]
Please re-open this or suggest a better location to track this bug.

**Comment by braydonf** [comment]
Please open on core https://github.com/storj/core for bridge-client and plans for how to implement best can be discussed.
