### ISSUE TITLE
Add Duplicate Bucket Error Code/Message

### ISSUE THREAD

**Issue by braydonf** [Storj/bridge#322]
When adding a duplicate bucket, currently an 500 "internal server error" error status is sent. This could be an idempotent call, and return 200 with the existing document. Otherwise a 400-range error status should be given to indicate that the bucket already exists.

**Comment by kaloyan-raev** [comment]
I prepared PR https://github.com/Storj/bridge/pull/569 that will make the bridge return 409 Conflict instead of 500 Internal Server Error. Note that the PR check currently fails because it requires PRs in another two modules to be merged first.
