### ISSUE TITLE
Bridge does not properly reconnect to mongodb after no mongos proxy available error

### ISSUE THREAD

**Issue by phutchins** [Storj/bridge#327]
### Package Versions

Bridge Version

```
storj-bridge@4.2.2 /opt/storj/bridge
└── (empty)
```

Node Version

```
v6.9.1
```

### Expected Behavior

```
When an issue is encountered with MongoDB, the application should continue to attempt to reconnect to the database until it is able to make a successful connection.
```

### Actual Behavior
The bridge process attempts to reconnect once and then does not retry again. 
```
{"level":"warn","message":"database connection closed, reconnecting...","timestamp":"2017-01-09T17:19:28.119Z"}
{"level":"info","message":"opening database connection to mongodb://dbserver.storj.io:27020/bridge","timestamp":"2017-01-09T17:19:28.119Z"}
{"level":"error","message":"failed to connect to database: no mongos proxy available","timestamp":"2017-01-09T17:19:28.121Z"}
```

### Steps to Reproduce

Not attempting to reproduce at the moment. If needed, we can do this.

This may be an issue in Mongoose. Also there is a possibility that using multiple mongos endpoints in the MongoDB URI might help although this should work regardless.

**Comment by braydonf** [comment]
The underlying driver has a `reconnect` property https://github.com/christkv/mongodb-core#connecting-to-mongodb

With the addition of `/health` endpoint, the database connected state can be determined at the load balancer and process management to revolve.

If this is reproducible, and reappears, let's reopen.
