### ISSUE TITLE
Bridge API continues to take traffic while it has no MongoDB connection

### ISSUE THREAD

**Issue by phutchins** [Storj/bridge#328]
### Package Versions

Storj Bridge Version

```
storj-bridge@4.2.2 /opt/storj/bridge
└── (empty)
```

Node Version

```
v6.9.1
```

### Expected Behavior

While an instance has no healthy MongoDB connection, it should not attempt to respond to requests and should return a 500 or 503 error. 503 would probably be most appropriate as it is relying on an external service that is not available.

Waiting for a DB connection to return for a few seconds seems like a reasonable idea but it should return before nginx's default upstream timeout as well as before nodejs's http(s), and in turn express's default request timeout which is 120 seconds. (see https://nodejs.org/api/http.html#http_server_timeout)

### Actual Behavior

Currently the process appears to accept the request but never respond, resulting in a timeout at the proxy level. 

```
2017/01/12 16:58:34 [error] 4883#0: *2598116 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 104.196.58.99, server: api.staging.storj.io, request: "GET /buckets?__nonce=1484240254300 HTTP/1.1", upstream: "http://104.196.54.27:8016/buckets?__nonce=1484240254300", host: "api.staging.storj.io", referrer: "https://app.staging.storj.io/"
```

### Steps to Reproduce

Put the bridge-api instance into a state where it does not have a mongodb connection and send it a request.

**Comment by braydonf** [comment]
This should be solved with the addition of `/health` endpoint https://github.com/Storj/bridge/pull/411 as load balancing can use this to direct traffic.
