### ISSUE TITLE
Inaccurate FreeTier up-/download.

### ISSUE THREAD

**Issue by Th3Van** [Storj/bridge#341]
### Package Versions

Replace the values below using the output from `node --version`.
```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your usage code in the back ticks below if applicable.

```
Bridge should offer FreeTier (UL/DL) like this : 
Hourly : 3 / 9 GB
Daily : 10 / 30 GB
Monthly : 60 / 180 GB
```
*Source : https://github.com/Storj/bridge/blob/4e07f77117932e8405dd0022b3eb728e0027765b/lib/config.js#L60-L71*

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces or log output in the back ticks below.

The Bridge's (FreeTier) does not seem to honor the 1:3 UL/DL hourly or daily values as described above.

*Test setup :*
*Server025.storj.dk running core-cli, and using api.storj.io as bridge.*

**First test:**
```
Using a new bridge account.

08:17 28-01-2017 - Incoming : 118.09 GB
08:17 28-01-2017 - Outgoing : 301.56 GB

Script is fired up..

08:22 28-01-2017 - Incoming : 124.01 GB (limit reached)
08:31 28-01-2017 - Outgoing : 320.47 GB (limit reached) 

Total Download (to server025) :  5.92 GB - [avg. : 157 Mbit/s]
Total Upload (from server025) : 18.91 GB - [avg. : 180 Mbit/s]
```
**Second test:**
```
Using a bridge account that has been idle for +24h: 

00:17 29-01-2017 - Incoming : 141.03 GB
00:17 29-01-2017 - Outgoing : 377.71 GB

Script is fired up..

00:20 29-01-2017 - Incoming : 146.56 GB (limit reached)
00:30 29-01-2017 - Outgoing : 413.01 GB (limit reached)

Total Download (to server025) :  5.53 GB - [avg. : 147 Mbit/s]
Total Upload (from server025) : 35.30 GB - [avg. : 362 Mbit/s]
```
**Third test:**
```
Using another bridge account, that also has been idle for +24h: 

00:49 29-01-2017 - Incoming : 146.92 GB
00:49 29-01-2017 - Outgoing : 414.03 GB

Script is fired up..

00:54 29-01-2017 - Incoming :  153.32 GB (limit reached) 
01:05 29-01-2017 - Outgoing :  446.51 GB (limit reached)

Total Download (to server025) :  6.40 GB - [avg. : 170 Mbit/s] - [peak @  751 Mbit/s]
Total Upload (from server025) : 32.48 GB - [avg. : 272 Mbit/s] - [peak @ 1210 Mbit/s]
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as much detail as possible.

1. Create a fresh new account @ api.storj.io
2. Create 100 x 100MB files using `Openssl rand -out fileblob001.tmp 104857600`
3. Create a script to continuously upload/ download those 100MB files using `core-cli`
4. Use unix/debian `nload` to measure the total amount of 0's and 1's (both up-/download)
5. Notice that you upload way more 0's and 1's  than FreeTiers allow :)

//Th3Van

**Comment by braydonf** [comment]
Likely related: https://github.com/Storj/service-storage-models/issues/41
