### ISSUE TITLE
Add improved logging and status of requests

### ISSUE THREAD

**Issue by braydonf** [Storj/bridge#357]
Periodically log health information about each server, possibly including some of the following info:
- server.getConnections https://nodejs.org/api/net.html#net_server_getconnections_callback
- server.listening https://nodejs.org/api/net.html#net_server_listening
- process.memoryUsage https://nodejs.org/api/process.html#process_process_memoryusage
- process.uptime https://nodejs.org/api/process.html#process_process_uptime
- process.cpuUsage https://nodejs.org/api/process.html#process_process_cpuusage_previousvalue

Other related methods:
- backlog in server.listen https://nodejs.org/api/net.html#net_server_listen_handle_backlog_callback
- server.maxConnections https://nodejs.org/api/net.html#net_server_maxconnections
- response.setTimeout https://nodejs.org/api/http.html#http_response_settimeout_msecs_callback
- server.setTimeout https://nodejs.org/api/http.html#http_server_settimeout_msecs_callback

Include logging for response time for each request:
- Log response times by endpoint using `morgan` or directly with `on-finished` and `on-headers` to include the response times for each request, thus average times can be calculated per endpoint.
- Keep track of each pending request by endpoint, and periodically log total pending

**Comment by phutchins** [comment]
This would be great. number of connections or current requests would be very handy.

Memory and CPU can be retrieved through Kubernetes in our production environment currently so we may leave those out of this. Uptime can be derived in a similar way but if its inexpensive it may be handy to have and helpful for others. 

Response time by endpoint would also be very helpful. We could get these from our reverse proxy and logstash but adding it in the app would be quite helpful for other users or local debugging.

**Comment by braydonf** [comment]
The memory usage from node may give us some insights, as it's aware of v8 heap vs external:
```
{
  rss: 4935680,
  heapTotal: 1826816,
  heapUsed: 650472,
  external: 49879
}
```
