### ISSUE TITLE
Can't create a storj account probably because my e-mail address domain has a newer suffix

### ISSUE THREAD

**Issue by swgutkind** [Storj/bridge#369]
See the following e-mail exchange with Storj Support:
#=#
Helene Unland replied to the post "Is my e-mail address considered valid because it is weird?".

Hi Sam, this problem will require a change to the code, so please open an issue in https://github.com/Storj/bridge/issues describing the problem you have encountered. Sorry for the inconvenience, and let us know if you need any assistance with opening the issue on github.
#=#

It may be because my e-mail address is sam.william.gutkind@noricon.systems. Or it may have been for some other reason.

Please get back to me,
Sam

[vvv]== I haven't downloaded the package yet. This problem seems to concern your website or backend.

**Comment by braydonf** [comment]
I've updated the above text to not include all the uncompleted template for issues.

**Comment by braydonf** [comment]
There should not be any issues with registering such email addresses, however there still a few areas in which email validation needs to be updated, and will be resolved with: https://github.com/Storj/service-storage-models/pull/74

**Comment by braydonf** [comment]
I've included a similar vector in the tests at https://github.com/Storj/service-storage-models/pull/74/files#diff-e0cf53206c1f87a4d136c04b391dca6bR9

**Comment by braydonf** [comment]
With both the bridge-gui and the storage models updated with validation, this should no longer be an issue. We can confirm this next week, and then close this issue.

**Comment by braydonf** [comment]
Email validation has been relaxed to only care about lengths, I've tested `user+something@domain.tld` style email addresses, and uploading/creating frames (which previously was not working) is now working.
