### ISSUE TITLE
Concurrency addShardToFrame calling during upload-file may lost some shard size counting to frame total size which would cause download-file failure

### ISSUE THREAD

**Issue by dxhome** [Storj/bridge#373]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
Latest bridge code
```

Replace the values below using the output from `node --version`.

```
v6.9.5
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
uploaded file should be download successfully always
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
file downloading will be failed because the bridge recorded frame size is less than real file size (also less than the size of all shards of frame)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

As this an concurrency issue, it is hard to provide reproduce steps. 
This issue would usually happen if several concurrent shard uploading (default concurrency is 3) complete and try to call bridge->addShardToFrame at same time. 

The problem should at below code pieces of lib/server/routes/frames.js 
As mongoDB doesn't support transaction among multiple collections update,  below codes execution may overwrite the previous committed frame.size in another thread, which happens between frame.findOne() and frame.save()  of current thread

           FramesRouter.prototype.addShardToFrame = function(req, res, next) {
              ...
                  if (!replaced) {
                       frame.size += pointer.size;
                  }
              ...
              }

Suggested solution:
1. pass file size to bridge as frame size instead of calculating it like the current
2. keep current logic and re-calculate frame size at createEntryFromFrame phrase

"1" seems simple but not sure if there is some other background not use it before.

**Comment by braydonf** [comment]
Also have noticed this behavior, a similar bug has been fixed and the same type of fix needs to be applied here.

**Comment by dxhome** [comment]
what are your preferred design for fix?

**Comment by braydonf** [comment]
We can use `$inc` in an update mongodb query, as similar to https://github.com/Storj/service-storage-models/pull/63
