### ISSUE TITLE
Keep cache of retrieval pointers

### ISSUE THREAD

**Issue by braydonf** [Storj/bridge#375]
- Have shard retrieval tokens to farmers expire in 24 hours (or similar)
- Keep TTL collections of pointers to farmers for downloading that are prepared in advance

**Comment by littleskunk** [comment]
TTL on the farmer side is 30 minutes: https://github.com/Storj/core/blob/master/lib/constants.js#L28

They will drop the token and will not open a data channel.

24 hours is not possible. Farmer will run out of memory.

**Comment by braydonf** [comment]
It may be worth it consider increasing from 30 minutes, but even a cache of 30 minutes may be useful.

**Comment by braydonf** [comment]
Condensing into https://github.com/Storj/bridge/issues/398
