### ISSUE TITLE
Libstorj add-bucket name shows up differently in app.storj.io 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#379]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@5.3.3 /home/gordon/Code/storj-bridge
└──Libstorj v1.0.0-beta2
```

Replace the values below using the output from `node --version`.

```
v6.10.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
My bucket names are the same as the names i added in the `add-bucket` command with libstorj 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
C:\libstorj-1.0.0-beta2\bin>storj list-buckets
ID: 88ba4d4e75210e1dece9222a    Decrypted: false        Name: ebooks
ID: 2d1e2f237ecc08143df0bd1f    Decrypted: true         Name: test
ID: 4484762f2d84eec955e4e3c2    Decrypted: false        Name: skunk
ID: ee455768f533ef39e0b62444    Decrypted: true         Name: thesis_Data

C:\libstorj-1.0.0-beta2\bin>
```

![bridge](https://cloud.githubusercontent.com/assets/11735738/23875986/55bfe55e-0833-11e7-8014-847cc40d550d.png)

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Add a bucket with libstorj
2. Login to app.storj.io and view the bucket names
3. ...

**Comment by braydonf** [comment]
Yes they are encrypted. This will be resolved with https://github.com/Storj/core/issues/661 and updates to the gui.

**Comment by braydonf** [comment]
Okay, moved this issue to bridge-gui.
