### ISSUE TITLE
Process that monitors established mirror counts per shard

### ISSUE THREAD

**Issue by braydonf** [Storj/bridge#383]
There is a case where a shard will have available mirrors, but will not have established the maximum of 5 default mirrors. We need to have a way to maintain at least this number of mirrors per shard.

**Comment by tempestb** [comment]
Suggestion -

  Once a week, a node will send the Bridge a list of all of the shards it currently has.  The Bridge stores this in a table.  Fields:

Record ID
Hash of Node.  
Hash of Shard/Contract.  
Added Datetime

  Once a week, the Bridge looks for any contract in the list that doesn't have 6 copies within the past week of updates.  It then orders Farmers to create a new mirror.

Obviously, you could also compare this against other data that you already have.  For instance, a node who is supposed to be a mirror but hasn't reported the shard, could have their contract canceled.

This would also provide a way to measure the health of the node.  If they continuously lose data (Such as the farmer erasing the shards for various reasons) you would know.  It would also tell you about any anomalies, such as contracts that should be expired but the shards are still present.  

Lastly, it would take the work load off the Bridge, having to audit all the shards all the time.  And instead make the farmer do a self audit and report in with its findings.

Just a suggestion.  No worries if it is stupid and deserves to be erased.  Mostly just thinking out loud to provide ideas.  Thanks.

**Comment by braydonf** [comment]
Condensing into https://github.com/Storj/bridge/issues/398
