### ISSUE TITLE
Cannot access public buckets without authenticating

### ISSUE THREAD

**Issue by frdwrd** [Storj/bridge#393]
### Expected Behavior

Un-authenticated users should be able to access files in public buckets. This includes pulling for buckets with the public `pull` permission set, and pushing for buckets with the public `push` permission set.

### Actual Behavior

Users must authenticate before attempting to push or pull from a public bucket, or get a `NotAuthorizedError` from the authentication middleware.

https://github.com/Storj/service-middleware/blob/master/lib/authenticate.js

### Steps to Reproduce

1. Create a public bucket
2. Upload a file to a public bucket
3. Log out of your account
4. Attempt to pull the file

**Comment by braydonf** [comment]
We can address when public shared files is fully implemented and spec'd: https://github.com/Storj/sips/pull/41

**Comment by braydonf** [comment]
Spec draft: https://github.com/Storj/sips/pull/41
