### ISSUE TITLE
List pointer may return incorrect point list

### ISSUE THREAD

**Issue by dxhome** [Storj/bridge#415]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
latest codes (1132.bc4a4ee)
```

Replace the values below using the output from `node --version`.

```
v6.10.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
List pointers should always be returned by right index order
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When the network (internet) is unstable between from farmer, it is mostly possible a shard will be completed late and added to frame.  A possible pointer records in mongo may like below.
   0, 1, 2 (bad), 3, 4, 5, 6, 7, 2 (good), ...  (number is index of shard)

Since the current code (_getPointersFromEntry) will load a range (default is 6) of pointers and then sort them. In above cases, the returned pointer list will totally mess up the order of pointers.

below is a proposed fix:
BucketsRouter.prototype._getPointersFromEntry = ...

   ....
  const indexStart = parseInt(opts.skip) || 0;
  const indexEnd = parseInt(opts.skip) + parseInt(opts.limit) || 6;

  let pQuery = {
    _id: { $in: entry.frame.shards }
  };
  let pSort = { index: 1 };

  let cursor = Pointer.find(pQuery).sort(pSort);
  cursor.exec(function(err, allPointers) {
    if (err) {
      return done(new errors.InternalError(err.message));
    }

    let pointers = allPointers.slice(indexStart, indexEnd);
    ...

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by braydonf** [comment]
If the pointer is completed late, the shard will be replaced in the frame (removing the incomplete shard from the frame), and it won't appear in the query since it will only search for shards that match those in the frame.

The `$lte` and `$gte` applies to `index`, which will return all entries within that range, and sorted. So even if shard 2 was uploaded after 7, it would still be in the correct order.

**Comment by braydonf** [comment]
Are there multiple pointers with the same index being returned?

**Comment by dxhome** [comment]
You are right. I just found there are some problem in record of frames. Close this issue
