### ISSUE TITLE
wrong shard order by index from list-mirrors

### ISSUE THREAD

**Issue by dxhome** [Storj/bridge#416]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
latest code
```

Replace the values below using the output from `node --version`.

```
v6.10.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
list-mirrors should always return correct shard order by index
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
sometimes (printers are not recorded in index order), list mirrors will return wrong shard order
in "_getHashesFromFrame", needs to sort results of Point.find(xxx) to get right point order.

proposed codes like:
   ...
       self.storage.models.Pointer.find({
      _id: { $in: frame.shards }
    }).sort({ index: 1 }).exec(function(err, pointers) {
   ... 

seems problem seems in "BucketsRouter.prototype.getPointersForEntry" as well
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by braydonf** [comment]
Condensing into https://github.com/Storj/bridge/issues/427
