### ISSUE TITLE
Wrong renterID is sending the contract -> DDOS FIND_NODE to locate renter

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#443]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
root@storj:~# storjshare --version

  * daemon: 2.5.4, core: 6.4.2, protocol: 1.1.0
```
```
info	
title	"Storj Bridge"
version	"5.15.0"
description	"Access the Storj network using a simple REST API."
x-protocol-version	"1.1.0"
x-core-version	"6.4.2"
```

Replace the values below using the output from `node --version`.

```
v6.10.3
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

The renter with a renterID close to the shard hash should send out the contract PUBLISH to the farmerID close to the shard hash. At the end I should only communicate with the same few renterID alle them time. Because these renterIDs are close to me I should have a permanent place on my shortlist for them.
```
{"level":"debug","message":"Sending offer for contract hash 18543e824dbd60a829dff22a5d21c0d80d723fa9","timestamp":"2017-05-11T22:49:41.861Z"}
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.4.0\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":3817,\"address\":\"renter-153.renters.prod.storj.io\",\"port\":8400,\"nodeID\":\"1a07ab8d2279b24e2ed03d8206db13340968a0ed\",\"lastSeen\":1494542601631}","timestamp":"2017-05-11T22:49:41.861Z"}
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Even renterIDs far away from the shard hash are sending out the shard hash. My farmer is unable to keep all renterIDs on the shortlist and will have to drop some of them. At the end all farmer are DDOS each other with FIND_NODE messages to locate the renter.

A few examples of far away renterIDs. The shard hash are more or less close to me.
```
{"level":"debug","message":"Sending offer for contract hash 17f299942c7b28b79bc1ae17ba7578924577cbaa","timestamp":"2017-05-11T22:49:34.500Z"}
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.4.0\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":13792,\"address\":\"renter-192.renters.prod.storj.io\",\"port\":8400,\"nodeID\":\"94af90d2bde83fc04a14ff6af69529d1d0fded88\",\"lastSeen\":1494542713147}","timestamp":"2017-05-11T22:49:34.500Z"}
{"level":"debug","message":"Sending offer for contract hash 18fd44fca4cb8f299cbc7f7d65c68ee68da13bef","timestamp":"2017-05-11T22:49:34.560Z"}
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.4.0\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":16501,\"address\":\"renter-224.renters.prod.storj.io\",\"port\":8400,\"nodeID\":\"da8a751aa21a19e70dd78a56a408d717755280df\",\"lastSeen\":1494542930903}","timestamp":"2017-05-11T22:49:34.560Z"}
{"level":"debug","message":"Sending offer for contract hash 1dfcb4a0b89c8a91d6a146df2fb4620234ed22dd","timestamp":"2017-05-11T22:49:35.069Z"}
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.4.0\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":8249,\"address\":\"renter-72.renters.prod.storj.io\",\"port\":8400,\"nodeID\":\"74d4c9a819483a806fa7dcc3c5199419d0783bca\",\"lastSeen\":1494542904464}","timestamp":"2017-05-11T22:49:35.069Z"}
{"level":"debug","message":"Sending offer for contract hash 110eee713fafe3229bce9d7c0029464eba03583d","timestamp":"2017-05-11T22:49:38.563Z"}
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.4.0\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":10830,\"address\":\"renter-91.renters.prod.storj.io\",\"port\":8400,\"nodeID\":\"edd2ea49a0a1429acfc1626cc3b8cd56d3290278\",\"lastSeen\":1494542901532}","timestamp":"2017-05-11T22:49:38.563Z"}
{"level":"debug","message":"Sending offer for contract hash 208d01004b7ecec774f4aede3e6239d1c5d577da","timestamp":"2017-05-11T22:49:40.729Z"}
{"level":"info","message":"sending OFFER message to {\"userAgent\":\"6.4.0\",\"protocol\":\"1.1.0\",\"hdKey\":\"xpub6AHweYHAxk1EhJSBctQD1nLWPog6Sy2eTpKQLExR1hfzTyyZQWvU4EYNXv1NJN7GpLYXnDLt4PzN874g6zSjAQdFCHZN7U7nbYKYVDUzD42\",\"hdIndex\":8624,\"address\":\"renter-118.renters.prod.storj.io\",\"port\":8400,\"nodeID\":\"cfe6da9403a5fc4c24f82371f3ee34220bf1887d\",\"lastSeen\":1494542811790}","timestamp":"2017-05-11T22:49:40.730Z"}
```

3891 sending FIND_NODE traffic in one hour
```
root@storj:~# grep 'sending FIND_NODE' .storjshare/storjshare/logs/188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep 2017-05-11T21 | wc -l
3891
```
4417 received FIND_NODE in one hour
```
root@storj:~# grep 'received FIND_NODE' .storjshare/storjshare/logs/188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep 2017-05-11T21 | wc -l
4417
```
427 could not locate renter -> no OFFER and most likely my neigbors are unable to send an OFFER as well.
```
root@storj:~# grep 'could not locate renter' .storjshare/storjshare/logs/188071ba7cfd974a9e47b59e24b0737ebf845db3.log | grep 2017-05-11T21 | wc -l
427
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. wait for a stresstest
2. grep logfile

**Comment by littleskunk** [comment]
locate renter is expensive. My farmer should locate my close renterIDs only once and than send OFFER as fast as possible. I would be able to send may concurrent OFFER because each of them needs only a few ms. Locate renter will block my farmer for a few seconds. I will ignore all other contracts because I have already too many concurrent OFFER.

**Comment by littleskunk** [comment]
Last but not least:
My farmer is running at 100% CPU now. That is the reason for the high OFFER timeout i can see on my logfile. I don't get any response on 50% of my OFFER messages. I guess because I am sending the OFFER to late and the bridge will drop it.

The stress test at 05.05.2017 was better. My farmer was only at 20% CPU. Any bad code change these days?

**Comment by felixbrucker** [comment]
ill test this with my farmers on next stress test, i too noticed very high cpu usage even though no transfers where currently ongoing

**Comment by AlexeyALeonov** [comment]
I have troubles with my routers with a lot of FIND_NODE messages. This is looking like DDOS attack and my router can't handle it.
Network usage is very low, But WAN is very overflooded
Firewall resists, but router can't answer and even start page not opened.
Of course in that time i have a troubles with connection to other sites and resources.

**Comment by littleskunk** [comment]
Moved to https://github.com/Storj/complex/issues/55
