### ISSUE TITLE
Validate login

### ISSUE THREAD

**Issue by SoftvalMedia** [Storj/bridge#445]
¿There's any way to validate user login with the api? If not, ¿can you add something to validate user login?

I want to build an app where you can login with your user and manage your nodes.

**Comment by bookchin** [comment]
There is not a specific login endpoint. You just authenticate via basic auth or ecdsa signature in whatever request. I believe the bridge gui does the login validation by doing a `POST /keys` with the basic auth method, then assuming a `200`, proceeding with everything by signing with the private portion of the public key posted to that endpoint.
