### ISSUE TITLE
Renegotiate storage contracts that will expire soon

### ISSUE THREAD

**Issue by bookchin** [Storj/bridge#46]
Bridge needs to periodically check for `BucketEntry`s that are close to their renewal time and automatically renegotiate the associated storage contract.

**Comment by gordonwritescode** [comment]
@niahmiah let's talk about this one in a week or two and pair up on it

**Comment by super3** [comment]
I believe we reset the DB for the last time 2 weeks ago. If we have 90 day contract expiry, then we contracts should start expiring sometime in August.

**Comment by bookchin** [comment]
Moved to https://github.com/Storj/service-auditor/issues/1
