### ISSUE TITLE
Option to list more than 2000 files from bucket

### ISSUE THREAD

**Issue by lucvanbraekel** [Storj/bridge#469]
### Package Versions

```
storj-bridge@5.22.1 
```

### Expected Behavior

Listing all files in a bucket can give a truncated list (currently: truncated at 2000), but possibility should exist to list ALL files in the bucket.

### Actual Behavior

DEFAULT_MAX_ENTRIES is hardcoded at 2000 in the bridge software.

### Steps to Reproduce

1. Upload more than 2000 files to a bucket.
2. storj list-files bucket-id
3. List will be truncated at 2000 files, no option exists to get more.

I'm adding this issue to bridge and not to libstorj, because the server must offer the option before the client can request it.

**Comment by braydonf** [comment]
There is already an option using the `startDate` query argument for both buckets and bucket entries.

**Comment by braydonf** [comment]
https://storj.io/api.html

**Comment by braydonf** [comment]
https://github.com/Storj/libstorj/issues/363
