### ISSUE TITLE
rebuild lost shards with erasure at the bridge - healing

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#479]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.2.3
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
The bridge rebuilds the missing shard and distributes it back the network.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Currently if a renter uploads a shard to a farmer and the farmer goes offline right after the transfer there will be a missing shard which can not be replicated.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by braydonf** [comment]
So this can be added to the storj-monitor when it's unable to replicate a shard around this area: https://github.com/Storj/bridge/blob/master/lib/monitor/index.js#L204-L218

**Comment by braydonf** [comment]
When a shard fails to replicate, that shard status can be updated, and another healing script can watch for those events and start to repair the files.

**Comment by MeijeSibbel** [comment]
related to https://github.com/Storj/core/issues/712

**Comment by braydonf** [comment]
This is already tracked with https://github.com/Storj/bridge/issues/395
