### ISSUE TITLE
Bridge monitor keeps pinging bad contacts

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#504]
```
{"level":"error","message":"Unable to save ping failure, farmer: 14d0f7a9aff6ee7f0830be7e6c0a210ae9dc48f7, reason: Contact validation failed: address: Path `address` is required.","timestamp":"2017-09-16T20:03:54.140Z"}
```

This farmer has a invalid address. The bridge monitor will never stop pinging him. There are a few other farmer with the same problem. At the end the bridge will run into an endless loop and stop pinging other farmer. 
https://api.storj.io/contacts/14d0f7a9aff6ee7f0830be7e6c0a210ae9dc48f7

That explains why I havents seen any mirror creation for one month now. We have to fix that to avoid lost shards.

**Comment by braydonf** [comment]
I've seen this for a different validation error, when we first started the service...

**Comment by braydonf** [comment]
All the errors here are for address being an empty string. So we can either add $exists: true for address before querying or we can assume it will fail the ping and save the timeoutRate above the threshold.

**Comment by braydonf** [comment]
I am curious how these contacts were created to begin with though.

**Comment by braydonf** [comment]
Looks like they are coming from an earlier version of the software that likely didn't have the validation, so a cleanup of these contacts is likely due.

**Comment by braydonf** [comment]
Okay, cleaned up, shouldn't be an issue anymore.
