### ISSUE TITLE
SIP6 is using only 9% of the network and cutting off 91% of the farmer

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#514]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
title | "Storj Bridge"
version | "7.0.2"
x-protocol-version | "1.2.0"
x-core-version | "8.2.0"
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

The bridge should utilize the complete network. A Pi3 farmer with a high uptime and a fast internet connection should get more shards than a 12/7 farmer with a slow internet connection.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

The bridge is sending a ALLOC message to 36 farmer with less than 9sec responseTime and 9 farmer with more than 9sec responseTime. The first answer gets the shard and the 5 mirrors will be selected by responseTime.

Lets calculate the current shard distibution:
4872 farmer with less than 9 sec responseTime. Per shard upload 36 will get an ALLOC message. One rotation needs 136 shards. One rotation will upload shards to 136 farmer and on the next rotation most likely the same 136 farmer again. Plus mirror creation and a few other effects the network is centralized on 1000 farmer only. 

91% of the farmer are not getting any shards at all. They are disconnected from the shard distribution and they are not able to improve responseTime.
Only 9% of the farmer are used. They are getting all the shards.

On the renter side I would expect slower transfers. Only 9% of the total bandwidth is used.

All farmer with lastSeen not older than 2 days
![total](https://user-images.githubusercontent.com/6333390/31321554-3cac5a08-ac88-11e7-9c9f-5c5bd1699635.jpg)

All farmer with lastSeen not older than 2 days and responseTime lower than 4sec
![lowresponsetime](https://user-images.githubusercontent.com/6333390/31321577-7503681a-ac88-11e7-8734-36ec7a5cf19e.jpg)

Note: The 4 sec line is a quick obversation from different farmer. The calculation is giving me even a lower number. By collecting the farmer responseTime movements over a few days I can calculate a better result.

Last but not least: Farmer please keep this issue clear. You can express your situation by voting for this issue. Spamming this issue with comments will only slow us down.
Renter comments are wellcome. You are the paying customers.

**Comment by Th3Van** [comment]
Coincidentally, I uploaded 53.039 files (each 66.6 MBytes in size) the last four days before SIP6 was activated.
Grepping the logs, I was able to upload those shards/files to 7.781 unique NodeID.

*[Upload-Test-66MB-Unique-NodeID-Before-SIP6-Th3Van.txt](https://github.com/Storj/bridge/files/1367289/Upload-Test-66MB-Unique-NodeID-Before-SIP6-Th3Van.txt)*

SIP6 are now activated, so I did try to run exact the same upload test a couple of time today, but I somehow ended up with a ton of `Upload failure: Unable to receive storage offer` after like an hour, so i had to terminate the test. However, I'll wait a few more days and run the test again, and post the result here for comparison. 

//Th3Van

**Comment by BlackDuck888** [comment]
Total fail of SIP6, as stated from Littleskunk before activation, if response time will be part of calculation. I am sad to say that he is correct, before SIP6 i was able to upload with 800mbit-1gbit, now i am down to 600mbit-800mbit, not bad at all, but less than before.  Understandable for me, why this hard change is not tested in a separate testnet, as pos!

**Comment by Jurisg** [comment]
Found 9 my nodes form 11 in Upload-Test-66MB-Unique-NodeID-Before-SIP6-Th3Van.txt.
As for uploading did 19 upload tests of 1GB files got some Upload failure: Unable to receive storage offer.
Most shards got uploaded very fast and upload failure i was getting when i get 1 very slow farmer node, with speed like ~500kbit/s so for them those 100mb+ shard will take ~30 minutes to finish upload and  most time it was failing with Upload failure: Unable to receive storage offer.
Saved all my upload logs if any want check them.

**Comment by braydonf** [comment]
responseTime has been updated on successful ALLOC, so that this metric can be improved before receiving shards. https://github.com/Storj/complex/releases/tag/v7.1.0

**Comment by littleskunk** [comment]
Reopen. The bridge is still using the first ALLOC response. The math of SIP6 is wrong. The bridge is using only 9% of the total network. Limited upload speed for the renter.

Mirror selection is now using timeoutRate. Please keep in mind that timeoutRate is not working. See https://github.com/Storj/service-storage-models/issues/96

We have 3354 farmer with 0 timeoutRate. More than 60% of the farmer has no chance to get 0 timeoutRate. The last bridge generated timeouts were 4 days ago and hit most of the farmer.

**I am able to simulate SIP6 with a little script.** As input I use the bridge contact list. Build two groups with plus and minus 9sec responseTime farmer and simulate 36 / 9 ALLOC messages. Which farmer has the lowest responseTime and which farmer will get the mirrors? The simulation should show the same result as we can see on the storj network. **We can simulate different settings to improve the situation.**

**Comment by 4Ykw** [comment]
I was hoping for someone to really have a try... that's great! I was feeling alone.

PS: How do you guys get those google maps overlays? Very Nice!

**Comment by BlackDuck888** [comment]
@4Ykw https://github.com/bobey/StorjMap

**Comment by braydonf** [comment]
Breaking this into specific issues:
- https://github.com/Storj/complex/issues/83
- https://github.com/Storj/complex/issues/81

**Comment by littleskunk** [comment]
Ok lets use these issue to track it.
