### ISSUE TITLE
Wrong IP address in api.storj.io

### ISSUE THREAD

**Issue by AntonMZ** [storj/bridge#519]
Hello.

I found any problem with https://api.storj.io Please check.

I can see on https://api.storj.io wrong ip addresses.

<hr/>

**Part 1 | Wrong format ip address. Many ' ' in ip address.**

You can see problem here [https://api.storj.io/contacts/ddfe494619644fd2b835ae04ca4ddd03652f9ebf](https://api.storj.io/contacts/ddfe494619644fd2b835ae04ca4ddd03652f9ebf)

`
{"spaceAvailable":true,"lastSeen":"2017-10-14T13:03:43.540Z","port":4000,"address":"1 7 7 . 2 2 8 . 3 5 . 1 9","protocol":"1.2.0","responseTime":43079.63710867344,"lastContractSent":1507759633784,"userAgent":"8.1.0","lastTimeout":"2017-10-10T17:01:15.427Z","timeoutRate":0.04549201388888889,"reputation":0,"nodeID":"ddfe494619644fd2b835ae04ca4ddd03652f9ebf"}
`

<hr/>

**Part 2 | Wrong format. Word in ip address.**

You can see problem here [https://api.storj.io/contacts/026a32beaedbe6350d44aace69ebf4886f3ec7f3](https://api.storj.io/contacts/026a32beaedbe6350d44aace69ebf4886f3ec7f3)

`{"lastSeen":"2017-10-14T13:54:25.144Z","port":3200,"address":"addr:192.168.0.111","userAgent":"6.6.0","protocol":"1.1.0","lastTimeout":"2017-07-10T10:59:43.957Z","timeoutRate":0.04768177083333333,"responseTime":10000,"nodeID":"026a32beaedbe6350d44aace69ebf4886f3ec7f3"}`

<hr/>

**Part 3 | Is not public ip address (127.0.0.1)**

You can see problem here [https://api.storj.io/contacts/77e14da2e55c4fbcc4853bc36942d823a350e674](https://api.storj.io/contacts/77e14da2e55c4fbcc4853bc36942d823a350e674)

`
{"spaceAvailable":true,"lastSeen":"2017-10-14T08:42:10.976Z","port":4000,"address":"127.0.0.1","protocol":"1.2.0","responseTime":1084.9168981736284,"userAgent":"8.1.0","lastContractSent":1507759603124,"reputation":3961,"lastTimeout":"2017-10-14T11:33:54.732Z","timeoutRate":0.04094861111111111,"nodeID":"77e14da2e55c4fbcc4853bc36942d823a350e674"}
`

<hr/>

**Part 4 | Wrong nslookup PTR. I can't resolve this host in ip address.**
This problem in many hosts in api.storj.io

You can see problem here [https://api.storj.io/contacts/dbc177a36062d9b1b9ef35a97e26924a3a3fe8f7](https://api.storj.io/contacts/dbc177a36062d9b1b9ef35a97e26924a3a3fe8f7)

`
{"lastSeen":"2017-10-14T14:05:52.620Z","port":4001,"address":"marazmas.ddns.net","userAgent":"8.1.0","protocol":"1.2.0","lastTimeout":"2017-10-11T05:18:18.410Z","timeoutRate":0.053986909722222226,"responseTime":42018.216384541505,"spaceAvailable":true,"lastContractSent":1507761091163,"reputation":0,"nodeID":"dbc177a36062d9b1b9ef35a97e26924a3a3fe8f7"}
`

<hr/>

**Part 5 | Strange IP address for node (100.112.168.134) It's special reserved address.**
Node was made in this address or it's error?

You can see problem here [https://api.storj.io/contacts/39ad1dadc2c29d4c359174ecada9acb4e018d1bb](https://api.storj.io/contacts/39ad1dadc2c29d4c359174ecada9acb4e018d1bb)

`
{"spaceAvailable":true,"lastSeen":"2017-10-14T14:07:34.887Z","port":4000,"address":"100.112.168.134","protocol":"1.2.0","responseTime":43204.896612403696,"lastContractSent":1507760687090,"userAgent":"8.1.0","reputation":0,"lastTimeout":"2017-10-11T20:00:24.754Z","timeoutRate":0.049746909722222225,"nodeID":"39ad1dadc2c29d4c359174ecada9acb4e018d1bb"}
`

<hr/>

**Part 6 | Local ip address (192.168.0.109)**

You can see problem here [https://api.storj.io/contacts/52b590991be60c028125b0dcfb2fc2b50e7dc50e](https://api.storj.io/contacts/52b590991be60c028125b0dcfb2fc2b50e7dc50e)

`
{"spaceAvailable":true,"lastSeen":"2017-10-14T05:52:26.674Z","port":4000,"address":"192.168.0.109","protocol":"1.2.0","responseTime":10784.981278825726,"reputation":0,"lastTimeout":"2017-10-14T08:26:34.669Z","timeoutRate":0.04307208333333333,"nodeID":"52b590991be60c028125b0dcfb2fc2b50e7dc50e"}
`

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
