### ISSUE TITLE
Rework data upload so that bridge does not proxy

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/bridge#52]
### Proposed Implementation

The current upload design will not scale and leaves bridge as a bottleneck for distributing files in the Storj network. We can rework the file upload so that bridge negotiates the shard contracts and authorizes data channels with the farmers, but returns that information to clients so they can upload directly.

#### Upload Flow

1. Client wishes to store a file and starts by issuing a:
  * `POST /frames`
  * This creates a staging area for a file
  * Returns a unique ID for the frame (staging area)
2. Client performs encryption/sharding and iterates for each encrypted shard:
  * `PUT /frames/:frame_id` + including metadata about shard
  * Bridge negotiates a contract and returns a datachannel consign token for the shard
  * Client opens datachannel with farmer and consigns the shard
3. Client is finished filling the frame and wishes to create a file pointer in bucket:
  * `POST /buckets/:bucket_id/files` + including the frame ID
  * Bridge uses the current snapshot of the frame to create a file pointer and bucket entry
  * Bridge responds with the identifier (file hash) for the file in the bucket

#### Control Flow

4. Client wishes to append more data to the frame and create a new file pointer
  * Follow *upload flow* steps 2 and 3 again
5. Client is finished with the frame and closes it by issuing a:
  * `DELETE /frames/:frame_id`
6. Client wishes to see all open frames by issuing a:
  * `GET /frames`
7. Client wishes to check the status of an individual frame:
  * `GET /frames/:frame_id`

**Comment by gordonwritescode** [comment]
Related storj/core#42

**Comment by phutchins** [comment]
This all sounds good. On the open/closed terminology, how would we define those? Is there a named state for a frame that has some of the shards that represent a file vs all?
