### ISSUE TITLE
No reputation for many nodes

### ISSUE THREAD

**Issue by AntonMZ** [Storj/bridge#520]
I can't find reputation for many nodes.

You can see error here

[https://api.storj.io/contacts/e10dcc2afbad6f76b1320b7068bf58fa2e86f867](https://api.storj.io/contacts/e10dcc2afbad6f76b1320b7068bf58fa2e86f867)
`
{"lastSeen":"2017-10-15T06:44:58.495Z","port":8400,"address":"renter-148.renters.prod.storj.io","userAgent":"8.3.0","protocol":"1.2.0","lastTimeout":"2017-06-01T17:55:44.457Z","timeoutRate":0.0436634375,"responseTime":10000,"nodeID":"e10dcc2afbad6f76b1320b7068bf58fa2e86f867"}
`

here

[https://api.storj.io/contacts/f78fb57e502b84890c2174e05dcf66fe03794c94](https://api.storj.io/contacts/f78fb57e502b84890c2174e05dcf66fe03794c94)

`
{"lastSeen":"2017-10-15T06:11:02.464Z","port":4001,"address":"cryptominiacz.storj.today","userAgent":"6.8.0","protocol":"1.1.0","responseTime":10207.773513436226,"lastTimeout":"2017-10-02T03:03:16.893Z","timeoutRate":0.04050143518518518,"nodeID":"f78fb57e502b84890c2174e05dcf66fe03794c94"}
`

and many other nodes (total nodes without reputation 3659).

**Comment by littleskunk** [comment]
Both without `spaceAvailable`. The bridge is working correct. If they don't have space for a new shard the bridge will not even ask them.
