### ISSUE TITLE
Frame is still locked after deleting the associated file

### ISSUE THREAD

**Issue by jkawamoto** [Storj/bridge#535]
[BucketsRouter.prototype.createEntryFromFrame](https://github.com/Storj/bridge/blob/master/lib/server/routes/buckets.js#L452) locks a frame for the creating file but [BucketsRouter.prototype.removeFile](https://github.com/Storj/bridge/blob/master/lib/server/routes/buckets.js#L1269) doesn’t release the lock after deleting the file.

If the lock is released, I think we can create another file from the frame with a different file name to implement [renaming files](https://github.com/Storj/libstorj/issues/398). (Currently, file name, i.e. file ID, is used to encrypt the file but I guess we can use the frame ID instead.)

**Comment by braydonf** [comment]
There is a fair amount of information on the bucket entry that needs to be retained for the purpose of renaming files. Renaming the bucket entry is something that can be done currently, with a few hard deprecations (see https://github.com/Storj/service-storage-models/blob/master/lib/models/bucketentry.js#L14-L23).

**Comment by braydonf** [comment]
We can track renaming files with https://github.com/Storj/bridge/issues/488
