### ISSUE TITLE
IPv6 support disabled on the bridge

### ISSUE THREAD

**Issue by littleskunk** [storj/bridge#545]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
{"title":"Storj Bridge","version":"7.3.1","description":"Access the Storj network using a simple REST API.","x-protocol-version":"1.2.0","x-core-version":"8.4.2"}
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Farmer with ipv6 should be able to receive shards.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

It looks like IPv6 support is disabled on the bridge. Farmer with IPv6 address is not receiving any ALLOC messages.

ALLOC timed out on the bridge log
```
{"level":"warn","message":"Error publishing contract to node:
 {\"_id\":\"9960192c8d0f42611eaba2c64cb474c8943ad283\",\"__v\":0,\"spaceAvailable\":true,\"lastSeen\":\"2017-12-04T22:07:38.908Z\",\"port\":1337,\"address\":\
"[2001:67c:2ed8:6100:2289:84ff:fe5e:e89d]\",\"protocol\":\"1.2.0\",\"responseTime\":12149.950891152504, "reputation\":0,\"userAgent\":\"8.3.1\"}, reason: RPC with ID `b5e1ffac95cac9cce4b47fc2cf06495a612c4d4d` timed out","timestamp":"2017-12-05T01:30:46.904Z"}
```

Timed out is expected in this case because KAD doesn't throw an error if IPv6 is disabled.
Log example from my farmer using the IPv6 farmer as seed but with disabled IPv6 support.
```
{"level":"info","message":"sending FIND_NODE message to {\"userAgent\":\"8.4.2\",\"protocol\":\"1.2.0\",\"address\":\"2001:67c:2ed8:6100:2289:84ff:fe5e:e89d\",\"port\":1337,\"nodeID\":\"9960192c8d0f42611eaba2c64cb474c8943ad283\",\"lastSeen\":1512429719105}","timestamp":"2017-12-04T23:21:59.114Z"}
{"level":"debug","message":"queuing callback for reponse to dad971aaf58fb92830347212962971800f7da7fa","timestamp":"2017-12-04T23:21:59.198Z"}
[...]
{"level":"warn","message":"rpc call dad971aaf58fb92830347212962971800f7da7fa timed out","timestamp":"2017-12-04T23:22:58.970Z"}
{"level":"debug","message":"removing contact {\"userAgent\":\"8.4.2\",\"protocol\":\"1.2.0\",\"address\":\"2001:67c:2ed8:6100:2289:84ff:fe5e:e89d\",\"port\":1337,\"nodeID\":\"9960192c8d0f42611eaba2c64cb474c8943ad283\",\"lastSeen\":1512429719105}","timestamp":"2017-12-04T23:22:58.970Z"}
{"level":"warn","message":"query failed, removing contact for shortlist, reason RPC with ID `dad971aaf58fb92830347212962971800f7da7fa` timed out","timestamp":"2017-12-04T23:22:58.971Z"}
{"level":"debug","message":"removing contact {\"userAgent\":\"8.4.2\",\"protocol\":\"1.2.0\",\"address\":\"2001:67c:2ed8:6100:2289:84ff:fe5e:e89d\",\"port\":1337,\"nodeID\":\"9960192c8d0f42611eaba2c64cb474c8943ad283\",\"lastSeen\":1512429719105}","timestamp":"2017-12-04T23:22:58.971Z"}
```

A PING request with IPv6 enabled was working. The farmer is online and he is receiving PUBLISH messages from other farmer with IPv6 support. The farmer is not receiving any ALLOC messages.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Setup an IPv6 farmer
2. Search on the bridge logfile by nodeID
3. Search on the farmer logfile for any ALLOC messages or by timestamp (bridge timestamp -90 sec)

**Comment by braydonf** [comment]
I think this is more of an operations task, no code changes should be required here.

**Comment by braydonf** [comment]
We can verify, at the least though.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
