### ISSUE TITLE
Can't list files in a bucket, app.storj.io won't load the dashboard 

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/bridge#550]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
latest
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
I can list my files in a bucket
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 500
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 500
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 500
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
  Request failed with status code: 0
Checking for changes...
```

same with fileZilla:

```
Status:	Connecting to api.storj.io...
Status:	Retrieving directory listing...
Status:	Directory listing of "/" successful
Status:	Retrieving directory listing of "/Goobox"...
Command:	list 8126211066cbe3545737fa40 
Error:	Request failed with status code 0
Error:	Failed to retrieve directory listing
Status:	Retrieving directory listing of "/Goobox"...
Command:	list 8126211066cbe3545737fa40 
Error:	Request failed with status code 0
Error:	Failed to retrieve directory listing
Status:	Retrieving directory listing of "/Goobox"...
Command:	list 8126211066cbe3545737fa40 
Error:	Request failed with status code 0
Error:	Failed to retrieve directory listing
Status:	Retrieving directory listing of "/"...
Status:	Directory listing of "/" successful
```

https://app.storj.io/dashboard/ also won't load, it continues to show the rotating storj logo.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. upload files to a bucket
2. try to retrieve the file listing
3. ...

**Comment by braydonf** [comment]
Related: https://github.com/Storj/libstorj/issues/404

**Comment by MeijeSibbel** [comment]
Just to clarify, there are about 4k files in that bucket.

**Comment by kaloyan-raev** [comment]
@MeijeSibbel it will be interesting to see if you can reproduce the same with your own instance of https://github.com/Storj/integration. If yes, then it should be easier to inspect the logs on the server.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
