### ISSUE TITLE
Bridge appears to "forget" about full node

### ISSUE THREAD

**Issue by gbaker3** [Storj/bridge#555]
I believe the issue is with the bridge, however I am seeing the problem through the behaviour of my node.

### Package Versions

Running on Windows 10 Pro 1709
```
GUI 7.3.1
Daemon 5.3.0
Core 8.5.0
Protocol 1.2.0
```

### Expected Behavior

_Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable._

When a node is filled to the point where it will no longer accept shards, I expect the bridge to stop sending ALLOC messages until the node has free space available. When full the reputation metric reduces to 0. Once space is freed, I expect the node to start receiving shards again and the reputation metric to increase.

### Actual Behavior

_Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below._

When the node is filled, the reputation metric gradually reduces to 0. As spaced is freed over time due to contracts expiring the node does not begin to receive new ALLOC messages. Even though the "last seen" time continues to update when the node is online, the reputation metric stays at zero and no new ALLOC messages are received by the node.

I have reproduced this problem twice. Both times, restarting the node fixed the problem, the node started receiving ALLOC messages, and the reputation metric increased. Even if restarting the node does fix the problem, it should not be necessary to restart the node as 100% uptime is the goal for highest reliability.

First occurance:
- Node filled to 291.3 / 300 GB (97%), reputation decreased to 0
- Contracts expired over a period of 3 months (zero downtime/restarts during this period)
- Node was at 18.6 / 300 GB (6%), no new ALLOC messages received during past 3 months
- Restarted node, node began receiving ALLOC messages, consignments handled, reputation increased

Reproducing the problem:
- Share size reduced to 40 GB. Node was storing 38.4 GB at this time (96%)
- Node continues to receive contracts, fills to 42.7 / 40 GB (107%)
- Reputation metric decreases to 0
- Contracts expired over a period of 2 weeks (zero downtime/restarts during this period)
- Node was at 30.9 / 40 GB (77%), no new ALLOC messages received
- Restarted node, node began receiving ALLOC messages, consignments handled, reputation increased (much slower recovery than first occurrence)

### Steps to Reproduce

_Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible._

1. Create a node and allow it to fill to the point where it stops receiving ALLOC messages (at or near 100%) and reputation goes to zero.

2. Keep node online without restarting until contracts expire and space is freed.

3. Watch as the node continues to free space via contracts expiring, but no new ALLOC messages are sent.

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/core/issues/752
