### ISSUE TITLE
Return http code 403 instead of 401 if account is not activated

### ISSUE THREAD

**Issue by kaloyan-raev** [Storj/bridge#570]
Currently, if the user account has not been activated yet, the bridge returns http code 401 Not Authorized - the same as if the user has provided invalid credentials.

This make it difficult for clients to distinguish between the two use cases without parsing the accompanying error message.

Moreover, http code 401 is not quite semantically correct for the 'account not activated yet' use case, because the [spec](https://httpstatuses.com/401) says:

> The request has not been applied because it lacks valid authentication credentials for the target resource.

In the case of 'account not activated yet' the user has provided valid credentials. So the above statement is not satisfied.

I think returning http code 403 Forbidden would be a better fit. The [spec](https://httpstatuses.com/403) about it says:

> The server understood the request but refuses to authorize it.

> If authentication credentials were provided in the request, the server considers them insufficient to grant access.

The above sounds legit for the 'account not activated yet' use case. Valid credentials were provided, but the server refuses to authorize the request due to another reason - the account has not been activated yet.

**Comment by braydonf** [comment]
Sounds like a good idea!

**Comment by kaloyan-raev** [comment]
Great! See https://github.com/Storj/bridge/pull/571 and the linked dependent PRs.
