### ISSUE TITLE
Performance enhancement contract renewal

### ISSUE THREAD

**Issue by littleskunk** [storj/bridge#587]
At the moment we have a very inperformant way to renew contract.

✔️ First we select all shards that would expire in the next 24 hours. https://github.com/Storj/bridge/blob/3dd818955c9f42d89a90ceafc8400793b138b931/bin/storj-contract-renew.js#L27-L32
❌ For each shard we select the 6 mirror contracts. Too early to increase the number of entries.
https://github.com/Storj/bridge/blob/3dd818955c9f42d89a90ceafc8400793b138b931/bin/storj-contract-renew.js#L70-L75
❌ For each shard * 6 mirror contract we select the farmer with a subquery. Too early and subqueries are slow. Today my farmer received 67 shards. In 89 days the subquery will select my farmer 67 times instead of once.
https://github.com/Storj/bridge/blob/3dd818955c9f42d89a90ceafc8400793b138b931/bin/storj-contract-renew.js#L87
❌ At the end we filter out shards that are deleted by the renter. We are using 3 subqueries for that.
https://github.com/Storj/bridge/blob/3dd818955c9f42d89a90ceafc8400793b138b931/bin/storj-contract-renew.js#L124
https://github.com/Storj/bridge/blob/3dd818955c9f42d89a90ceafc8400793b138b931/bin/storj-contract-renew.js#L130
https://github.com/Storj/bridge/blob/3dd818955c9f42d89a90ceafc8400793b138b931/bin/storj-contract-renew.js#L140
✔️ Finaly we update the contract if the farmer confirmed the renew request.
https://github.com/Storj/bridge/blob/3dd818955c9f42d89a90ceafc8400793b138b931/bin/storj-contract-renew.js#L150

Instead of running 4 subqueries I would expect one "inner join".
The order for the selection should be:
* Select shards that would expire in the next 24 hours.
* Filter out shards that are deleted by the renter. (without BucketEntry)
* Multiply the result with the 6 mirrors contract.
* Add the farmer contact informations.

**Comment by littleskunk** [comment]
For a single shards we are executing the maximum number of subqueries:
```Contract push
Contract push
Contract push
Contract push
Contract push
Contact.findOne
Contact.findOne
Contact.findOne
Contact.findOne
Contact.findOne
Pointer.find
Pointer.find
Pointer.find
Pointer.find
Pointer.find
Frame.find
Frame.find
Frame.find
Frame.find
Frame.find
BucketEntry.find
Send Renew to farmer
BucketEntry.find
Send Renew to farmer
BucketEntry.find
Send Renew to farmer
BucketEntry.find
Send Renew to farmer
BucketEntry.find
Send Renew to farmer```
Only Contact.findOne will return 5 different datasets. We are selecting the same Pointer, Frame and BucketEntry 5 times in a row each.

In case of a deleted shard I would expect 15 subqueries. That is too expensive. We need to filter them out early.

I have problems to get the "inner join" working. Mongodb doesn't like array foreignFields.
```
storage.models.Shard.aggregate([
  {
    $match: {
      'contracts.contract.store_end': {
        $gte: NOW,
        $lte: NOW + HOURS_24
      }
    }
  },
  {
    $lookup: {
      from: 'frames',
      localField: '_id',
      foreignField: 'shards',
      as: 'frameData'
    }
  },
  {
    $unwind: {
      path: '$frameData'
    }
  }], function(err, shards) {
    console.log(shards);
    process.exit();
  });
```

**Comment by littleskunk** [comment]
@pgerbes1 
At the moment implemented is:
```
FOR each shard expires in the next 24hours
	FOR each contract in shards.contracts
		Get farmer contact
		IF frame exists and pointer exists and bucketEntry exists THEN
			send RENEW to farmer
		END IF
	END FOR
END FOR
```
The 4 subqueries farmer, frame, pointer and bucketEntry will be executed 5 times for each shard.

Better would be this:
```
FOR each shard expires in the next 24hours
	IF frame exists and pointer exits and bucketEntry exists THEN
		FOR each contract in shards.contracts
			Get farmer contact
			send RENEW to farmer
		END FOR
	END IF
END FOOR
```
Run the inner loop only if the shard was not deleted by the renter. That way the query for frame, pointer and bucketEntry need to be executed only once. The inner loop sill have to query 5 different farmer.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
