### ISSUE TITLE
SIP9 full 5000 reputation for bad farmer

### ISSUE THREAD

**Issue by littleskunk** [storj/bridge#596]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
{"title":"Storj Bridge",
"version":"8.0.0",
"description":"Access the Storj network using a simple REST API.",
"x-protocol-version":"1.2.0-STAGING",
"x-core-version":"8.7.2"}
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

I am running a bad farmer. The client or any other farmer is unable to download shards from me. I would expect 0 reputation.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

I get +1 for responding to alloc, +10 for the shard upload and +1 for the failed RETRIEVE request. I get full 5000 reputation 12 times faster. On the current mainnet version I would get only +1. That would at least slow me down for a while.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Contact me if you want to reproduce it. I have a test farmer ready.

**Comment by braydonf** [comment]
Okay here is an overview of every place that reputation is modified:

Base points:

- -1 if a request times out to a farmer at https://github.com/storj/complex/blob/587332873b583839196d1ce592bc8e9f76cc6c2d/lib/landlord.js#L233
- +1 if a request is successful to a farmer at https://github.com/storj/complex/blob/80d061ff72e1975d7180a377eef274ad3423179a/lib/landlord.js#L410
- -1 if a publish contract message to a farmer errors or times out at https://github.com/storj/complex/blob/80d061ff72e1975d7180a377eef274ad3423179a/lib/renter.js#L660
- +1 point if a publish contract message was successful https://github.com/storj/complex/blob/80d061ff72e1975d7180a377eef274ad3423179a/lib/renter.js#L679


Additions from SIP9:

- +10 points for a successful shard transfer https://github.com/storj/bridge/blob/master/lib/cron/storage-events.js#L123
- -10 points for a failed shard transfer at https://github.com/storj/bridge/blob/master/lib/cron/storage-events.js#L125
- -1000 points as an offline penalty https://github.com/storj/bridge/blob/master/lib/monitor/index.js#L284

**Comment by braydonf** [comment]
Here are the places that "reputation" is being used:

Reputation is NOT yet being used for PRIMARY initial "active" and "benchmark" pools, "responseTime" is currently being used there still, see: https://github.com/storj/bridge/blob/master/lib/server/routes/frames.js#L160-L187

Reputation is being used for SECONDARY selection of replication/mirror, after that initial selection query. See https://github.com/storj/bridge/blob/master/lib/server/routes/reports.js#L347

Reputation is being used for SECONDARY selection of cached offers at https://github.com/storj/bridge/blob/master/lib/server/routes/frames.js#L358

**Comment by braydonf** [comment]
And an overview of the actively used API methods:
`getRetrievalPointer` (RETRIEVE)
  - Renter side: https://github.com/storj/core/blob/master/lib/network/renter.js#L230
  - Farmer side: https://github.com/storj/core/blob/master/lib/network/protocol.js#L441
`publishContract` (ALLOC)
  - Renter side: https://github.com/storj/core/blob/master/lib/network/renter.js#L65
  - Farmer side: https://github.com/storj/core/blob/master/lib/network/farmer.js#L766
`getMirrorNodes` (MIRROR)
  - Renter side: https://github.com/storj/core/blob/master/lib/network/renter.js#L280
  - Farmer side: https://github.com/storj/core/blob/master/lib/network/protocol.js#L326
