### ISSUE TITLE
Need ability to configure confirmation email port

### ISSUE THREAD

**Issue by phutchins** [Storj/bridge#69]
When loadbalancing to the bridge servers we may use a different port than default and need to be able to change that when sending out confirmation email links.

**Comment by gordonwritescode** [comment]
* https://github.com/Storj/bridge/blob/master/lib/server/routes/users.js#L47
* https://github.com/Storj/bridge/blob/master/lib/config.js#L74

**Comment by phutchins** [comment]
This changes the actual port not port that the email link uses. The actual listening port and port in email confirmation link need to be able to be different.

**Comment by gordonwritescode** [comment]
Yes, just showing where the value comes from.

**Comment by niahmiah** [comment]
The server.host section of the config seems to only be used for the email, so I went ahead and moved it into the public section too. So, if you create a server.public object, it has to have both a host and port. Otherwise, it falls back to using the old format (server host and port).
