### ISSUE TITLE
failed to discover seeds from bridge - 504 Gateway timeout

### ISSUE THREAD

**Issue by 537b90c3** [Storj/bridge#92]
Raspbian Jessie - kernel 4.4 release 05-27-16

Trying to farm, telemetry reports are success and nat traversal are successful
attempt to publish message on topic then subscribe to topics
error: failed to discover seeds from bridge - gateway timeout

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/bridge/issues/91
